import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh' | 'ms' | 'ta';

interface UserProfile {
  id: string;
  name: string;
  nric: string;
  chasType: 'Blue' | 'Orange' | 'Green' | 'Merdeka generation' | 'Pioneer generation';
  points: number;
  participationHistory: string[];
}

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  user: UserProfile | null;
  setUser: (user: UserProfile | null) => void;
  isVoiceEnabled: boolean;
  setIsVoiceEnabled: (enabled: boolean) => void;
  isTtsEnabled: boolean;
  setIsTtsEnabled: (enabled: boolean) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Scan screen
    'scan.title': 'Welcome',
    'scan.subtitle': 'Please scan your IC / CHAS card to continue',
    'scan.instruction': 'Place your card on the scanner',
    'scan.scanning': 'Scanning...',
    'scan.success': 'Scan successful!',
    'scan.loading': 'Loading your profile...',
    
    // Language selection
    'lang.title': 'Choose Your Language',
    'lang.subtitle': 'Select your preferred language',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.title': 'How can we help you today?',
    'dashboard.health': 'Health Screenings',
    'dashboard.health.desc': 'Check your blood pressure, height & weight',
    'dashboard.findcare': 'Find Care',
    'dashboard.findcare.desc': 'Find nearby CHAS clinics',
    'dashboard.community': 'Community Programmes',
    'dashboard.community.desc': 'Join health talks & activities',
    'dashboard.profile': 'My Profile',
    'dashboard.profile.desc': 'View your points & rewards',
    'dashboard.medications': 'Your Medications',
    'dashboard.medications.desc': 'View prescribed medications',
    
    // Find Care - CCN Framing
    'findcare.title': 'Community Care Near You',
    'findcare.titleSubtext': 'Community Care Network – Singapore',
    'findcare.subtitle': 'Find care and support services in your neighbourhood',
    'findcare.ccnIntro1': 'The Community Care Network helps seniors and caregivers find care and support services near their home.',
    'findcare.ccnIntro2': 'Community-based care allows help to be accessed early, close to home, and within the neighbourhood.',
    'findcare.howItWorks': 'How Community Care Works',
    'findcare.howItWorks1': 'Community clinics and polyclinics are often the first point of care',
    'findcare.howItWorks2': 'Hospitals are for specialist or emergency care',
    'findcare.howItWorks3': 'Early community support helps seniors stay independent',
    'findcare.gpLabel': 'Community GP (Primary Care)',
    'findcare.polyclinicLabel': 'Polyclinic (Community Care)',
    'findcare.hospitalLabel': 'Hospital (Specialist Care)',
    'findcare.partOfCommunity': 'Part of community-based care',
    'findcare.ccnNudge': 'Community care is often the best first step for non-emergencies.',
    'findcare.helpCloser': 'Help is closer than you think.',
    'findcare.whyMatters': 'Why Community Care Matters',
    'findcare.whyMattersText': 'Community Care Network services help seniors and caregivers access support early, reduce unnecessary hospital visits, and receive care closer to home.',
    'findcare.ccnFooter': 'This page supports Community Care Network awareness by helping users understand community-based care options in Singapore.',
    'findcare.all': 'All',
    'findcare.polyclinics': 'Polyclinics',
    'findcare.hospitals': 'Hospitals',
    'findcare.gpClinic': 'GP Clinic',
    'findcare.dentalClinic': 'Dental',
    'findcare.polyclinic': 'Polyclinic',
    'findcare.hospital': 'Hospital',
    'findcare.call': 'Call',
    'findcare.directions': 'Get Directions',
    'findcare.emergencyTitle': 'For emergencies:',
    'findcare.emergencyDesc': 'Call 995 for ambulance or go to the nearest A&E.',
    'findcare.call995': 'Call 995',
    'findcare.searchPlaceholder': 'Search by name, address or postal code',
    'findcare.allRegions': 'All Regions',
    'findcare.resultsCount': '{count} clinics found',
    'findcare.noResults': 'No clinics found matching your search',
    'findcare.chasNoticeTitle': 'CHAS Subsidies:',
    'findcare.chasNoticeDesc': 'Show your CHAS card at these clinics to receive subsidised healthcare.',
    'findcare.mapView': 'Map',
    'findcare.listView': 'List',
    'findcare.distance': 'Distance',
    'findcare.nearbyClinics': 'Nearby Clinics',
    'findcare.within': 'within',
    'findcare.km': 'km',
    'findcare.kmAway': 'km away',
    'findcare.clinicsFound': 'clinics',
    'findcare.loading': 'Loading...',
    'findcare.loadingClinics': 'Loading clinics...',
    'findcare.located': 'Located',
    'findcare.findMe': 'Find Me',
    'findcare.recenter': 'Recenter',
    'findcare.clinicTypes': 'Clinic Types',
    'findcare.yourLocation': 'Your Location',
    'findcare.viewHours': 'View Hours',
    'findcare.openingHours': 'Opening Hours',
    'findcare.fetchHours': 'Fetch Hours',
    'findcare.gp': 'GP',
    'findcare.dental': 'Dental',
    'findcare.contactNumber': 'Contact Number',
    'findcare.callNow': 'Call Now',
    
    // Medications
    'meds.title': 'Your Medications',
    'meds.yourMeds': 'Prescribed Medications',
    'meds.pastMeds': 'Past Medications',
    'meds.pastMedsDesc': 'Your ongoing and completed prescriptions',
    'meds.orderMeds': 'Order Medications',
    'meds.orderMedsDesc': 'Select medications to reorder',
    'meds.lastOrder': 'Last ordered',
    'meds.perBox': 'per box',
    'meds.tablets': 'tablets',
    'meds.purpose.bp': 'Blood pressure management',
    'meds.purpose.chronic': 'Chronic condition support',
    'meds.purpose.digestive': 'Digestive health support',
    'meds.purpose.general': 'General health support',
    'meds.status.ongoing': 'Ongoing',
    'meds.status.completed': 'Completed',
    'meds.status.upcoming': 'Upcoming',
    'meds.delivery.scheduled': 'Scheduled for home delivery',
    'meds.delivery.ready': 'Ready for collection',
    'meds.delivery.shipped': 'On the way',
    'meds.delivery.delivered': 'Delivered',
    'meds.prescriber.polyclinic': 'Prescribed by Polyclinic doctor',
    'meds.prescriber.hospital': 'Prescribed by Hospital specialist',
    'meds.deliveryTitle': 'Delivery Options',
    'meds.deliveryInfo': 'Medications from teleconsultation can be delivered to your home.',
    'meds.delivery.home': 'Home Delivery',
    'meds.delivery.clinic': 'Collect at Clinic',
    'meds.paymentTitle': 'Payment Options',
    'meds.payment.card': 'Card Payment',
    'meds.payment.bill': 'Pay Later',
    'meds.payment.billDesc': 'Bill delivered for cash payment',
    'meds.disclaimer': 'Medication information shown here is for reference only. Please follow instructions given by your doctor or pharmacist.',
    'meds.selectClinic': 'Select Collection Clinic',
    'meds.orderSummary': 'Order Summary',
    'meds.subtotal': 'Subtotal',
    'meds.chasSubsidy': 'CHAS Subsidy',
    'meds.deliveryFee': 'Delivery Fee',
    'meds.selfCollection': 'Self Collection',
    'meds.free': 'FREE',
    'meds.total': 'Total',
    'meds.cardPayment': 'Card Payment',
    'meds.cardNumber': 'Card Number',
    'meds.cardHolder': 'Cardholder Name',
    'meds.expiryDate': 'Expiry Date',
    'meds.totalAmount': 'Total Amount',
    'meds.processing': 'Processing Payment...',
    'meds.payConfirm': 'Pay & Confirm Order',
    'meds.securePayment': 'Your payment is secured with SSL encryption',
    'meds.billCash': 'Bill to Home (Cash Payment)',
    'meds.billDeliveryTitle': 'Payment Bill Delivery',
    'meds.billDeliveryInfo': 'A payment bill will be sent with your medications. Pay in cash when it arrives.',
    'meds.billClinicInfo': 'Pay at the clinic counter when collecting your medications.',
    'meds.fullName': 'Full Name',
    'meds.blockNo': 'Block/House No.',
    'meds.unitNo': 'Unit No.',
    'meds.street': 'Street Name',
    'meds.postalCode': 'Postal Code',
    'meds.amountDue': 'Amount Due (Pay Later)',
    'meds.confirming': 'Confirming...',
    'meds.confirmOrder': 'Confirm Order',
    'meds.agreePayBill': 'By proceeding, you agree to pay when the order arrives.',
    'meds.collectAt': 'Collect at selected clinic',
    'meds.clinicAddress': 'Please bring your IC/CHAS card',
    'meds.orderPlaced': 'Order Placed Successfully',
    'meds.orderPlacedDesc': 'Your medication order has been confirmed.',
    'meds.continuePayment': 'Continue to Payment',
    'meds.step1': 'Select Medications',
    'meds.step2': 'Delivery & Payment',
    'meds.step3': 'Confirmation',
    'meds.statusUpdate': 'Delivery Status Updated',
    
    // Health screenings
    'health.title': 'Health Screenings',
    'health.bp': 'Blood Pressure',
    'health.bp.desc': 'Measure your blood pressure',
    'health.weight': 'Height & Weight',
    'health.weight.desc': 'Record your measurements',
    'health.back': 'Back to Menu',
    'health.result': 'Your Result',
    'health.normal': 'Normal',
    'health.date': 'Measured on',
    'health.pastResults': 'Past Results',
    'health.recommendedForYou': 'Recommended For You',
    'health.basedOnScreening': 'Based on your health screening',
    'health.findingProgrammes': 'Finding programmes for you...',
    'health.analyzingResults': 'Analyzing your health results',
    'health.recommendationError': 'Could not load recommendations',
    'health.viewAllProgrammes': 'View All Programmes',
    'health.saved': 'Result saved successfully',
    'health.saveFailed': 'Failed to save result',
    
    // Teleconsult
    'teleconsult.title': 'Teleconsultation',
    'teleconsult.subtitle': 'Speak to a doctor from home',
    'teleconsult.polyclinic': 'Polyclinic Doctor',
    'teleconsult.hospital': 'Hospital Specialist',
    'teleconsult.serious': 'For serious conditions, please visit a polyclinic or hospital in person.',
    'teleconsult.payment': 'Payment Options',
    'teleconsult.card': 'Pay by Card',
    'teleconsult.cash': 'Bill to Home (Cash)',
    'teleconsult.start': 'Start Consultation',
    'teleconsult.connecting': 'Connecting to doctor...',
    'teleconsult.connected': 'Consultation Started',
    'teleconsult.connected.desc': 'Your video consultation has been opened in a new browser tab.',
    'teleconsult.failed': 'Connection Failed',
    'teleconsult.failed.desc': 'Unable to start the teleconsultation. Please try again.',
    'teleconsult.tryAgain': 'Try Again',
    'teleconsult.goBack': 'Go Back',
    'teleconsult.returnDashboard': 'Return to Dashboard',
    'teleconsult.selectType': 'Select Consultation Type',
    'teleconsult.continuePayment': 'Continue to Payment',
    'teleconsult.payByCard': 'Pay by Card',
    'teleconsult.billHome': 'Bill to Home',
    'teleconsult.cardPayment': 'Card Payment',
    'teleconsult.cardNumber': 'Card Number',
    'teleconsult.cardHolder': 'Cardholder Name',
    'teleconsult.expiry': 'Expiry Date',
    'teleconsult.totalAmount': 'Total Amount',
    'teleconsult.processing': 'Processing Payment...',
    'teleconsult.payStart': 'Pay & Start Consultation',
    'teleconsult.securePayment': 'Your payment is secured with SSL encryption',
    'teleconsult.billCash': 'Bill to Home (Cash Payment)',
    'teleconsult.billDelivery': 'Payment Bill Delivery',
    'teleconsult.billInfo': 'A payment bill will be sent to your address. Pay in cash when it arrives within 3-5 working days.',
    'teleconsult.fullName': 'Full Name',
    'teleconsult.blockNo': 'Block/House No.',
    'teleconsult.unitNo': 'Unit No.',
    'teleconsult.street': 'Street Name',
    'teleconsult.postalCode': 'Postal Code',
    'teleconsult.amountDue': 'Amount Due (Pay Later)',
    'teleconsult.confirming': 'Confirming...',
    'teleconsult.confirmStart': 'Confirm & Start Consultation',
    'teleconsult.agreePayBill': 'By proceeding, you agree to pay the bill when it arrives at your address.',
    'teleconsult.consultFee': 'Consultation Fee',
    'teleconsult.free': 'FREE',
    'teleconsult.subsidisedRate': 'Subsidised rate for {cardType} cardholders',
    'teleconsult.polyclinicDoctor': 'Polyclinic Doctor',
    'teleconsult.hospitalSpecialist': 'Hospital Specialist',
    
    // Community
    'community.title': 'Community Programmes',
    'community.subtitle': 'Join activities near you',
    'community.upcoming': 'Upcoming Events',
    'community.past': 'Past Events',
    'community.signup': 'Register Interest',
    'community.signed': 'Signed Up',
    'community.reviews': 'Reviews',
    'community.points': 'points',
    'community.filterAll': 'All',
    'community.filterActive': 'Exercise',
    'community.filterHealth': 'Health Talks',
    'community.filterSocial': 'Social',
    'community.filterCaregiver': 'Caregiver',
    'community.filterDigital': 'Digital',
    'community.programmesFound': 'programmes found',
    'community.clearFilter': 'Clear filter',
    'community.noProgrammes': 'No programmes found',
    'community.noCompletedProgrammes': 'No completed programmes yet',
    'community.spotsLeft': 'spots left',
    'community.fullCapacity': 'Full',
    'community.moreDetails': 'More details',
    'community.eligibility': 'Who can join',
    'community.learningObjectives': 'What you will learn',
    'community.conductedBy': 'Conducted by',
    'community.howToJoin': 'How to join',
    'community.registerOnline': 'Register online using the form below',
    'community.callToBook': 'Call to book your spot',
    'community.walkInWelcome': 'Walk-in welcome, no booking needed',
    'community.lastUpdated': 'Last updated',
    'community.quarterlyReview': 'Programmes are reviewed and updated every 3 months.',
    'community.programmeNote': 'Programme information is reviewed and updated quarterly by Community Care Network administrators.',
    'community.signupFor': 'Register Interest',
    'community.yourName': 'Your Name',
    'community.enterName': 'Enter your name',
    'community.phoneNumber': 'Phone Number',
    'community.confirmSignup': 'Confirm Registration',
    'community.submitting': 'Submitting...',
    'community.callToRegister': 'Please call to register for this programme:',
    'community.walkinInfo': 'No registration needed. Just come on the day!',
    'community.signupSuccess': 'Successfully signed up!',
    'community.seeYouThere': 'We look forward to seeing you.',
    'community.signupFailed': 'Sign up failed. Please try again.',
    'community.fillAllFields': 'Please fill in all fields',
    'community.invalidPhone': 'Please enter a valid Singapore phone number',
    'community.feedbackTitle': 'Quick Feedback',
    'community.wasHelpful': 'Was this information helpful?',
    'community.optionalComment': 'Any comments? (Optional)',
    'community.commentPlaceholder': 'Tell us what you think...',
    'community.submitFeedback': 'Submit Feedback',
    'community.feedbackThanks': 'Thank you for your feedback!',
    'community.feedbackSubmitted': 'Your feedback helps us improve our services.',
    'community.voiceRecorded': 'Voice recorded successfully',
    'community.speakNow': 'Speak now...',
    'community.tapToSpeak': 'Tap to speak',
    'community.tapToStop': '🔴 Recording... Tap the button to stop',
    'community.voiceHint': 'Tap the microphone to speak your feedback',
    'community.cancel': 'Cancel',
    'community.cancelSuccess': 'Participation cancelled successfully',
    'community.cancelError': 'Failed to cancel. Please try again.',
    'community.yourProgrammes': 'Your Programmes',
    'community.allProgrammes': 'All Programmes',
    'community.contactOrganiser': 'Contact Organiser',
    'community.caregiverWelcome': 'Caregiver Welcome',
    'community.bringFriend': 'Bring a Friend',
    'community.thankyouRegistering': 'Thank you for registering your interest.',
    'community.organiserContact': 'The organiser will contact you if needed.',
    'community.completed': 'Completed',
    'community.registrationClosed': 'Registration Closed',
    'community.programmeStarted': 'Registration is closed as the programme has started.',
    'community.leaveFeedback': 'Leave Feedback',
    'community.shareFeedback': 'Share Your Feedback',
    'community.rateExperience': 'How was your experience?',
    'community.participantFeedback': 'Participant Feedback',
    'community.feedbackAlreadySubmitted': 'You have already submitted feedback for this programme.',
    'community.feedbackError': 'Failed to submit feedback. Please try again.',
    'community.feedbackSubmittedShort': 'Feedback Submitted',
    'community.cannotCancelStarted': 'Cannot cancel as the programme has already started.',
    'community.onlineProgramme': 'Online Programme',
    'community.joinOnline': 'Join Meeting',
    'community.needDirections': 'Need directions to the venue?',
    'community.printGuide': 'Print Getting There Guide',
    'community.printing': 'Printing...',
    'community.printed': 'Guide Printed!',
    'community.printSuccess': 'Directions guide printed successfully!',
    'community.close': 'Close',
    'community.completedProgrammes': 'Completed Programmes',
    'community.completedProgrammesDesc': 'View past events and leave reviews',
    'community.deleteFeedback': 'Delete Feedback?',
    'community.deleteFeedbackConfirm': 'This will permanently delete your feedback. This action cannot be undone.',
    'community.feedbackDeleted': 'Feedback deleted',
    'community.feedbackDeleteError': 'Failed to delete feedback',
    'community.updateFeedback': 'Update Feedback',
    'community.feedbackUpdated': 'Feedback updated',
    'community.tapToView': 'Tap to view',
    'community.eventsAttended': 'events attended',
    'community.you': 'You',
    'common.delete': 'Delete',
    // Profile
    'profile.title': 'My Profile',
    'profile.chas': 'CHAS Card Type',
    'profile.points': 'Total Points',
    'profile.history': 'Participation History',
    'profile.rewards': 'Redeem Rewards',
    'profile.redeemRewards': 'Redeem Rewards',
    'profile.voucher': 'Voucher',
    'profile.redeem': 'Redeem',
    'profile.quantity': 'Quantity',
    'profile.perVoucher': 'per voucher',
    'profile.totalPoints': 'Total points needed',
    'profile.needMorePoints': 'Need {points} more points',
    'profile.noHistory': 'No programme participation yet',
    'profile.joinProgrammes': 'Join community programmes to earn points!',
    'profile.deliveryAddress': 'Delivery Address',
    'profile.enterAddress': 'Enter your address for reward delivery:',
    'profile.pointsDeduct': 'Points to deduct',
    'profile.confirmRedeem': 'Confirm & Redeem',
    'profile.processing': 'Processing...',
    'profile.rewardRedeemed': 'Reward Redeemed!',
    'profile.willBeSent': 'will be sent to your home.',
    'profile.notEnoughPoints': 'Not enough points',
    'profile.fillAddress': 'Please fill in your address',
    'profile.needAddress': 'We need your address to deliver the reward.',
    'profile.redemptionFailed': 'Redemption Failed',
    'profile.tryAgainLater': 'Please try again later.',
    'profile.eventsAttended': 'Events Attended',
    'profile.progressToTier': 'Progress to Tier',
    'profile.allTiersUnlocked': 'All tiers unlocked!',
    'profile.tierLocked': 'Tier Locked',
    'profile.attendMoreEvents': 'Attend events to unlock. Required:',
    'profile.eventsRequired': 'events required',
    'profile.equipped': 'Equipped',
    'profile.unequipMedal': 'Unequip Medal',
    'profile.print': 'Print',
    'profile.maxedOut': 'Max Redeemed',
    'profile.trophyRack': 'Trophy Rack',
    'profile.tapToEquip': 'Tap to equip',
    'profile.remaining': 'remaining',
    'profile.maxQuantity': 'Max',
    'profile.browseProgrammes': 'Browse Programmes',
    'profile.historySubtitle': 'Your redeemed rewards and achievements',
    'profile.certificates': 'Certificates',
    'profile.dailyBonusRule': 'Earn 5 points daily! Login bonus resets at 12am.',
    'profile.dailyBonusClaimed': 'Daily Bonus Claimed!',
    'profile.dailyBonusDesc': 'You earned 5 bonus points for logging in today.',
    
    // Accessibility
    'access.translate': 'Translate',
    'access.voice': 'Voice Guide',
    'access.voiceOn': 'Voice On',
    'access.voiceOff': 'Voice Off',
    
    // Common
    'common.back': 'Back',
    'common.next': 'Next',
    'common.done': 'Done',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.logout': 'Log Out',
    'common.yes': 'Yes',
    'common.no': 'No',
  },
  zh: {
    'scan.title': '欢迎',
    'scan.subtitle': '请扫描您的身份证/CHAS卡以继续',
    'scan.instruction': '将您的卡放在扫描器上',
    'scan.scanning': '扫描中...',
    'scan.success': '扫描成功！',
    'scan.loading': '正在加载您的资料...',
    
    'lang.title': '选择您的语言',
    'lang.subtitle': '选择您偏好的语言',
    
    'dashboard.welcome': '欢迎',
    'dashboard.title': '今天我们能如何帮助您？',
    'dashboard.health': '健康检查',
    'dashboard.health.desc': '检查血压、身高和体重',
    'dashboard.findcare': '寻找医疗',
    'dashboard.findcare.desc': '查找附近的CHAS诊所',
    'dashboard.community': '社区活动',
    'dashboard.community.desc': '参加健康讲座和活动',
    'dashboard.profile': '我的资料',
    'dashboard.profile.desc': '查看积分和奖励',
    'dashboard.medications': '您的药物',
    'dashboard.medications.desc': '查看处方药物',
    
    // Find Care - CCN Framing
    'findcare.title': '您附近的社区护理',
    'findcare.titleSubtext': '社区护理网络 – 新加坡',
    'findcare.subtitle': '在您的邻里找到护理和支持服务',
    'findcare.ccnIntro1': '社区护理网络帮助年长者和护理者在家附近找到护理和支持服务。',
    'findcare.ccnIntro2': '社区护理让帮助能够尽早获得，就在家门口和邻里之间。',
    'findcare.howItWorks': '社区护理如何运作',
    'findcare.howItWorks1': '社区诊所和综合诊所通常是护理的第一站',
    'findcare.howItWorks2': '医院用于专科或紧急护理',
    'findcare.howItWorks3': '早期社区支持帮助年长者保持独立',
    'findcare.gpLabel': '社区家庭诊所（基层护理）',
    'findcare.polyclinicLabel': '综合诊所（社区护理）',
    'findcare.hospitalLabel': '医院（专科护理）',
    'findcare.partOfCommunity': '属于社区护理',
    'findcare.ccnNudge': '对于非紧急情况，社区护理通常是最佳第一步。',
    'findcare.helpCloser': '帮助就在您身边。',
    'findcare.whyMatters': '为什么社区护理很重要',
    'findcare.whyMattersText': '社区护理网络服务帮助年长者和护理者尽早获得支持，减少不必要的医院就诊，在家附近获得护理。',
    'findcare.ccnFooter': '本页面通过帮助用户了解新加坡社区护理选项来支持社区护理网络的宣传。',
    'findcare.all': '全部',
    'findcare.polyclinics': '综合诊所',
    'findcare.hospitals': '医院',
    'findcare.gpClinic': '家庭诊所',
    'findcare.dentalClinic': '牙科',
    'findcare.polyclinic': '综合诊所',
    'findcare.hospital': '医院',
    'findcare.call': '致电',
    'findcare.directions': '获取导航',
    'findcare.emergencyTitle': '紧急情况：',
    'findcare.emergencyDesc': '拨打995叫救护车或前往最近的急诊室。',
    'findcare.call995': '拨打995',
    'findcare.searchPlaceholder': '按名称、地址或邮政编码搜索',
    'findcare.allRegions': '所有地区',
    'findcare.resultsCount': '找到 {count} 家诊所',
    'findcare.noResults': '没有找到符合您搜索条件的诊所',
    'findcare.chasNoticeTitle': 'CHAS补贴：',
    'findcare.chasNoticeDesc': '在这些诊所出示您的CHAS卡即可享受医疗补贴。',
    'findcare.mapView': '地图',
    'findcare.listView': '列表',
    'findcare.distance': '距离',
    'findcare.nearbyClinics': '附近的诊所',
    'findcare.within': '范围',
    'findcare.km': '公里',
    'findcare.kmAway': '公里',
    'findcare.clinicsFound': '家诊所',
    'findcare.loading': '加载中...',
    'findcare.loadingClinics': '正在加载诊所...',
    'findcare.located': '已定位',
    'findcare.findMe': '定位我',
    'findcare.recenter': '重新定位',
    'findcare.clinicTypes': '诊所类型',
    'findcare.yourLocation': '您的位置',
    'findcare.viewHours': '查看营业时间',
    'findcare.openingHours': '营业时间',
    'findcare.fetchHours': '获取时间',
    'findcare.gp': '家庭诊所',
    'findcare.dental': '牙科',
    'findcare.contactNumber': '联系电话',
    'findcare.callNow': '立即拨打',
    
    // Medications
    'meds.title': '您的药物',
    'meds.yourMeds': '处方药物',
    'meds.pastMeds': '过往药物',
    'meds.pastMedsDesc': '您正在进行和已完成的处方',
    'meds.orderMeds': '订购药物',
    'meds.orderMedsDesc': '选择要重新订购的药物',
    'meds.lastOrder': '上次订购',
    'meds.perBox': '每盒',
    'meds.tablets': '片',
    'meds.purpose.bp': '血压管理',
    'meds.purpose.chronic': '慢性病支持',
    'meds.purpose.digestive': '消化健康支持',
    'meds.purpose.general': '一般健康支持',
    'meds.status.ongoing': '进行中',
    'meds.status.completed': '已完成',
    'meds.status.upcoming': '即将开始',
    'meds.delivery.scheduled': '已安排送货上门',
    'meds.delivery.ready': '可领取',
    'meds.delivery.shipped': '配送中',
    'meds.delivery.delivered': '已送达',
    'meds.prescriber.polyclinic': '综合诊所医生处方',
    'meds.prescriber.hospital': '医院专科医生处方',
    'meds.deliveryTitle': '配送方式',
    'meds.deliveryInfo': '远程医疗开出的药物可以送到您家。',
    'meds.delivery.home': '送货上门',
    'meds.delivery.clinic': '到诊所领取',
    'meds.paymentTitle': '付款方式',
    'meds.payment.card': '刷卡付款',
    'meds.payment.bill': '稍后付款',
    'meds.payment.billDesc': '账单寄到家现金支付',
    'meds.disclaimer': '此处显示的药物信息仅供参考。请遵循您的医生或药剂师的指示。',
    'meds.selectClinic': '选择领取诊所',
    'meds.orderSummary': '订单摘要',
    'meds.subtotal': '小计',
    'meds.chasSubsidy': 'CHAS补贴',
    'meds.deliveryFee': '配送费',
    'meds.selfCollection': '自取',
    'meds.free': '免费',
    'meds.total': '总计',
    'meds.cardPayment': '刷卡付款',
    'meds.cardNumber': '卡号',
    'meds.cardHolder': '持卡人姓名',
    'meds.expiryDate': '有效期',
    'meds.totalAmount': '总金额',
    'meds.processing': '处理付款中...',
    'meds.payConfirm': '付款并确认订单',
    'meds.securePayment': '您的付款通过SSL加密保护',
    'meds.billCash': '账单寄到家（现金付款）',
    'meds.billDeliveryTitle': '账单寄送',
    'meds.billDeliveryInfo': '账单将与药物一起寄送。收到后现金付款。',
    'meds.billClinicInfo': '在诊所柜台领取药物时付款。',
    'meds.fullName': '全名',
    'meds.blockNo': '门牌号',
    'meds.unitNo': '单位号',
    'meds.street': '街道名称',
    'meds.postalCode': '邮政编码',
    'meds.amountDue': '应付金额（稍后付款）',
    'meds.confirming': '确认中...',
    'meds.confirmOrder': '确认订单',
    'meds.agreePayBill': '继续即表示您同意在收到订单时付款。',
    'meds.collectAt': '在所选诊所领取',
    'meds.clinicAddress': '请携带您的身份证/CHAS卡',
    'meds.orderPlaced': '订单已成功提交',
    'meds.orderPlacedDesc': '您的药物订单已确认。',
    'meds.continuePayment': '继续付款',
    'meds.step1': '选择药物',
    'meds.step2': '配送和付款',
    'meds.step3': '确认',
    'meds.statusUpdate': '配送状态已更新',
    
    'health.title': '健康检查',
    'health.bp': '血压',
    'health.bp.desc': '测量您的血压',
    'health.weight': '身高和体重',
    'health.weight.desc': '记录您的测量数据',
    'health.back': '返回菜单',
    'health.result': '您的结果',
    'health.normal': '正常',
    'health.date': '测量日期',
    'health.pastResults': '过往结果',
    'health.recommendedForYou': '为您推荐',
    'health.basedOnScreening': '根据您的健康检查结果',
    'health.findingProgrammes': '正在为您寻找活动...',
    'health.analyzingResults': '正在分析您的健康数据',
    'health.recommendationError': '无法加载推荐',
    'health.viewAllProgrammes': '查看所有活动',
    'health.saved': '结果保存成功',
    'health.saveFailed': '保存结果失败',
    
    'teleconsult.title': '远程医疗',
    'teleconsult.subtitle': '在家与医生交谈',
    'teleconsult.polyclinic': '综合诊所医生',
    'teleconsult.hospital': '医院专科医生',
    'teleconsult.serious': '如有严重情况，请亲自前往综合诊所或医院。',
    'teleconsult.payment': '付款方式',
    'teleconsult.card': '刷卡付款',
    'teleconsult.cash': '账单寄到家（现金）',
    'teleconsult.start': '开始咨询',
    'teleconsult.connecting': '正在连接医生...',
    'teleconsult.connected': '咨询已开始',
    'teleconsult.connected.desc': '您的视频咨询已在新标签页中打开。',
    'teleconsult.failed': '连接失败',
    'teleconsult.failed.desc': '无法启动远程医疗，请重试。',
    'teleconsult.tryAgain': '重试',
    'teleconsult.goBack': '返回',
    'teleconsult.returnDashboard': '返回主页',
    'teleconsult.selectType': '选择咨询类型',
    'teleconsult.continuePayment': '继续付款',
    'teleconsult.payByCard': '刷卡付款',
    'teleconsult.billHome': '账单寄到家',
    'teleconsult.cardPayment': '刷卡付款',
    'teleconsult.cardNumber': '卡号',
    'teleconsult.cardHolder': '持卡人姓名',
    'teleconsult.expiry': '有效期',
    'teleconsult.totalAmount': '总金额',
    'teleconsult.processing': '处理付款中...',
    'teleconsult.payStart': '付款并开始咨询',
    'teleconsult.securePayment': '您的付款通过SSL加密保护',
    'teleconsult.billCash': '账单寄到家（现金付款）',
    'teleconsult.billDelivery': '账单寄送',
    'teleconsult.billInfo': '账单将寄送到您的地址。在3-5个工作日内收到后现金付款。',
    'teleconsult.fullName': '全名',
    'teleconsult.blockNo': '门牌号',
    'teleconsult.unitNo': '单位号',
    'teleconsult.street': '街道名称',
    'teleconsult.postalCode': '邮政编码',
    'teleconsult.amountDue': '应付金额（稍后付款）',
    'teleconsult.confirming': '确认中...',
    'teleconsult.confirmStart': '确认并开始咨询',
    'teleconsult.agreePayBill': '继续即表示您同意在账单到达后付款。',
    'teleconsult.consultFee': '咨询费用',
    'teleconsult.free': '免费',
    'teleconsult.subsidisedRate': '{cardType}持卡人补贴价',
    'teleconsult.polyclinicDoctor': '综合诊所医生',
    'teleconsult.hospitalSpecialist': '医院专科医生',
    
    'community.title': '社区活动',
    'community.subtitle': '参加您附近的活动',
    'community.upcoming': '即将举行的活动',
    'community.past': '过往活动',
    'community.signup': '登记兴趣',
    'community.signed': '已报名',
    'community.reviews': '评价',
    'community.points': '积分',
    'community.filterAll': '全部',
    'community.filterActive': '运动',
    'community.filterHealth': '健康讲座',
    'community.filterSocial': '社交',
    'community.filterCaregiver': '护理者',
    'community.filterDigital': '数码',
    'community.programmesFound': '个活动',
    'community.clearFilter': '清除筛选',
    'community.noProgrammes': '未找到活动',
    'community.noCompletedProgrammes': '暂无已完成的活动',
    'community.spotsLeft': '剩余名额',
    'community.fullCapacity': '已满',
    'community.moreDetails': '更多详情',
    'community.eligibility': '谁可以参加',
    'community.learningObjectives': '您将学到什么',
    'community.conductedBy': '主讲者',
    'community.howToJoin': '如何参加',
    'community.registerOnline': '使用下方表格在线报名',
    'community.callToBook': '致电预约',
    'community.walkInWelcome': '欢迎直接到场，无需预约',
    'community.lastUpdated': '最后更新',
    'community.quarterlyReview': '活动每3个月审核和更新一次。',
    'community.programmeNote': '活动信息由社区护理网络管理员每季度审核和更新。',
    'community.signupFor': '登记兴趣',
    'community.yourName': '您的姓名',
    'community.enterName': '输入您的姓名',
    'community.phoneNumber': '电话号码',
    'community.confirmSignup': '确认登记',
    'community.submitting': '提交中...',
    'community.callToRegister': '请致电报名此活动：',
    'community.walkinInfo': '无需报名，当天直接来即可！',
    'community.signupSuccess': '报名成功！',
    'community.seeYouThere': '期待您的到来。',
    'community.signupFailed': '报名失败，请重试。',
    'community.fillAllFields': '请填写所有字段',
    'community.invalidPhone': '请输入有效的新加坡电话号码',
    'community.feedbackTitle': '快速反馈',
    'community.wasHelpful': '这些信息对您有帮助吗？',
    'community.optionalComment': '有什么意见吗？（可选）',
    'community.commentPlaceholder': '告诉我们您的想法...',
    'community.submitFeedback': '提交反馈',
    'community.feedbackThanks': '感谢您的反馈！',
    'community.feedbackSubmitted': '您的反馈有助于我们改进服务。',
    'community.voiceRecorded': '语音录制成功',
    'community.speakNow': '请开始说话...',
    'community.tapToSpeak': '点击说话',
    'community.tapToStop': '🔴 录音中... 点击按钮停止',
    'community.voiceHint': '点击麦克风说出您的反馈',
    'community.cancel': '取消',
    'community.cancelSuccess': '已成功取消参与',
    'community.cancelError': '取消失败。请重试。',
    'community.yourProgrammes': '您已报名的活动',
    'community.allProgrammes': '所有活动',
    'community.contactOrganiser': '联系主办方',
    'community.caregiverWelcome': '欢迎看护者',
    'community.bringFriend': '可带朋友',
    'community.thankyouRegistering': '感谢您登记兴趣。',
    'community.organiserContact': '主办方会在需要时联系您。',
    'community.onlineProgramme': '线上活动',
    'community.joinOnline': '加入会议',
    'community.needDirections': '需要前往场地的路线吗？',
    'community.printGuide': '打印路线指南',
    'community.printing': '打印中...',
    'community.printed': '指南已打印！',
    'community.printSuccess': '路线指南已成功打印！',
    'community.close': '关闭',
    'community.completedProgrammes': '已完成的活动',
    'community.completedProgrammesDesc': '查看过去的活动并留下评价',
    'community.deleteFeedback': '删除反馈？',
    'community.deleteFeedbackConfirm': '这将永久删除您的反馈。此操作无法撤消。',
    'community.feedbackDeleted': '反馈已删除',
    'community.feedbackDeleteError': '删除反馈失败',
    'community.updateFeedback': '更新反馈',
    'community.feedbackUpdated': '反馈已更新',
    'community.tapToView': '点击查看',
    'community.eventsAttended': '次活动参与',
    'community.you': '您',
    'common.delete': '删除',
    
    'profile.title': '我的资料',
    'profile.chas': 'CHAS卡类型',
    'profile.points': '总积分',
    'profile.history': '参与记录',
    'profile.rewards': '兑换奖励',
    'profile.redeemRewards': '兑换奖励',
    'profile.voucher': '礼券',
    'profile.redeem': '兑换',
    'profile.quantity': '数量',
    'profile.perVoucher': '每张礼券',
    'profile.totalPoints': '所需总积分',
    'profile.needMorePoints': '还需 {points} 积分',
    'profile.noHistory': '暂无参与记录',
    'profile.joinProgrammes': '参加社区活动赚取积分！',
    'profile.deliveryAddress': '配送地址',
    'profile.enterAddress': '输入您的地址以接收奖励：',
    'profile.pointsDeduct': '扣除积分',
    'profile.confirmRedeem': '确认兑换',
    'profile.processing': '处理中...',
    'profile.rewardRedeemed': '兑换成功！',
    'profile.willBeSent': '将送到您家。',
    'profile.notEnoughPoints': '积分不足',
    'profile.fillAddress': '请填写地址',
    'profile.needAddress': '我们需要您的地址来配送奖励。',
    'profile.redemptionFailed': '兑换失败',
    'profile.tryAgainLater': '请稍后再试。',
    'profile.eventsAttended': '已参加活动',
    'profile.progressToTier': '进度至等级',
    'profile.allTiersUnlocked': '所有等级已解锁！',
    'profile.tierLocked': '等级锁定',
    'profile.attendMoreEvents': '参加活动以解锁。需要：',
    'profile.eventsRequired': '个活动',
    'profile.equipped': '已装备',
    'profile.unequipMedal': '卸下徽章',
    'profile.print': '打印',
    'profile.maxedOut': '已达上限',
    'profile.trophyRack': '奖杯架',
    'profile.tapToEquip': '点击装备',
    'profile.remaining': '剩余',
    'profile.maxQuantity': '上限',
    'profile.browseProgrammes': '浏览活动',
    'profile.historySubtitle': '您兑换的奖励和成就',
    'profile.certificates': '证书',
    'profile.dailyBonusRule': '每日可赚取5积分！登录奖励在凌晨12点重置。',
    'profile.dailyBonusClaimed': '已领取每日奖励！',
    'profile.dailyBonusDesc': '您今天登录获得了5积分奖励。',
    
    'access.translate': '翻译',
    'access.voice': '语音指南',
    'access.voiceOn': '语音开启',
    'access.voiceOff': '语音关闭',
    
    'common.back': '返回',
    'common.next': '下一步',
    'common.done': '完成',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.logout': '登出',
    'common.yes': '是',
    'common.no': '否',
  },
  ms: {
    'scan.title': 'Selamat Datang',
    'scan.subtitle': 'Sila imbas kad IC / CHAS anda untuk meneruskan',
    'scan.instruction': 'Letakkan kad anda pada pengimbas',
    'scan.scanning': 'Mengimbas...',
    'scan.success': 'Imbasan berjaya!',
    'scan.loading': 'Memuatkan profil anda...',
    
    'lang.title': 'Pilih Bahasa Anda',
    'lang.subtitle': 'Pilih bahasa pilihan anda',
    
    'dashboard.welcome': 'Selamat Datang',
    'dashboard.title': 'Bagaimana kami boleh membantu anda hari ini?',
    'dashboard.health': 'Pemeriksaan Kesihatan',
    'dashboard.health.desc': 'Periksa tekanan darah, tinggi & berat badan',
    'dashboard.findcare': 'Cari Rawatan',
    'dashboard.findcare.desc': 'Cari klinik CHAS berdekatan',
    'dashboard.community': 'Program Komuniti',
    'dashboard.community.desc': 'Sertai ceramah & aktiviti kesihatan',
    'dashboard.profile': 'Profil Saya',
    'dashboard.profile.desc': 'Lihat mata & ganjaran anda',
    'dashboard.medications': 'Ubat Anda',
    'dashboard.medications.desc': 'Lihat ubat yang ditetapkan',
    
    // Find Care - CCN Framing
    'findcare.title': 'Penjagaan Komuniti Berdekatan',
    'findcare.titleSubtext': 'Rangkaian Penjagaan Komuniti – Singapura',
    'findcare.subtitle': 'Cari perkhidmatan penjagaan dan sokongan di kejiranan anda',
    'findcare.ccnIntro1': 'Rangkaian Penjagaan Komuniti membantu warga emas dan penjaga mencari perkhidmatan penjagaan berdekatan rumah.',
    'findcare.ccnIntro2': 'Penjagaan berasaskan komuniti membolehkan bantuan diakses awal, dekat dengan rumah, dan dalam kejiranan.',
    'findcare.howItWorks': 'Bagaimana Penjagaan Komuniti Berfungsi',
    'findcare.howItWorks1': 'Klinik komuniti dan poliklinik sering menjadi titik penjagaan pertama',
    'findcare.howItWorks2': 'Hospital adalah untuk penjagaan pakar atau kecemasan',
    'findcare.howItWorks3': 'Sokongan komuniti awal membantu warga emas kekal berdikari',
    'findcare.gpLabel': 'GP Komuniti (Penjagaan Primer)',
    'findcare.polyclinicLabel': 'Poliklinik (Penjagaan Komuniti)',
    'findcare.hospitalLabel': 'Hospital (Penjagaan Pakar)',
    'findcare.partOfCommunity': 'Sebahagian daripada penjagaan komuniti',
    'findcare.ccnNudge': 'Penjagaan komuniti sering menjadi langkah pertama terbaik untuk bukan kecemasan.',
    'findcare.helpCloser': 'Bantuan lebih dekat dari yang anda sangka.',
    'findcare.whyMatters': 'Mengapa Penjagaan Komuniti Penting',
    'findcare.whyMattersText': 'Perkhidmatan Rangkaian Penjagaan Komuniti membantu warga emas dan penjaga mendapat sokongan awal, mengurangkan lawatan hospital yang tidak perlu, dan menerima penjagaan lebih dekat dengan rumah.',
    'findcare.ccnFooter': 'Halaman ini menyokong kesedaran Rangkaian Penjagaan Komuniti dengan membantu pengguna memahami pilihan penjagaan berasaskan komuniti di Singapura.',
    'findcare.all': 'Semua',
    'findcare.polyclinics': 'Poliklinik',
    'findcare.hospitals': 'Hospital',
    'findcare.gpClinic': 'Klinik GP',
    'findcare.dentalClinic': 'Pergigian',
    'findcare.polyclinic': 'Poliklinik',
    'findcare.hospital': 'Hospital',
    'findcare.call': 'Hubungi',
    'findcare.directions': 'Dapatkan Arah',
    'findcare.emergencyTitle': 'Untuk kecemasan:',
    'findcare.emergencyDesc': 'Hubungi 995 untuk ambulans atau pergi ke A&E terdekat.',
    'findcare.call995': 'Hubungi 995',
    'findcare.searchPlaceholder': 'Cari mengikut nama, alamat atau poskod',
    'findcare.allRegions': 'Semua Kawasan',
    'findcare.resultsCount': '{count} klinik dijumpai',
    'findcare.noResults': 'Tiada klinik ditemui yang sepadan dengan carian anda',
    'findcare.chasNoticeTitle': 'Subsidi CHAS:',
    'findcare.chasNoticeDesc': 'Tunjukkan kad CHAS anda di klinik ini untuk menerima rawatan kesihatan bersubsidi.',
    'findcare.mapView': 'Peta',
    'findcare.listView': 'Senarai',
    'findcare.distance': 'Jarak',
    'findcare.nearbyClinics': 'Klinik Berdekatan',
    'findcare.within': 'dalam',
    'findcare.km': 'km',
    'findcare.kmAway': 'km jauh',
    'findcare.clinicsFound': 'klinik',
    'findcare.loading': 'Memuatkan...',
    'findcare.loadingClinics': 'Memuatkan klinik...',
    'findcare.located': 'Dikesan',
    'findcare.findMe': 'Cari Saya',
    'findcare.recenter': 'Pusat Semula',
    'findcare.clinicTypes': 'Jenis Klinik',
    'findcare.yourLocation': 'Lokasi Anda',
    'findcare.viewHours': 'Lihat Waktu',
    'findcare.openingHours': 'Waktu Operasi',
    'findcare.fetchHours': 'Dapatkan Waktu',
    'findcare.gp': 'GP',
    'findcare.dental': 'Pergigian',
    'findcare.contactNumber': 'Nombor Hubungan',
    'findcare.callNow': 'Hubungi Sekarang',
    
    // Medications
    'meds.title': 'Ubat Anda',
    'meds.yourMeds': 'Ubat yang Ditetapkan',
    'meds.pastMeds': 'Ubat Lepas',
    'meds.pastMedsDesc': 'Preskripsi sedang berjalan dan selesai anda',
    'meds.orderMeds': 'Pesan Ubat',
    'meds.orderMedsDesc': 'Pilih ubat untuk dipesan semula',
    'meds.lastOrder': 'Pesanan terakhir',
    'meds.perBox': 'sekotak',
    'meds.tablets': 'tablet',
    'meds.purpose.bp': 'Pengurusan tekanan darah',
    'meds.purpose.chronic': 'Sokongan penyakit kronik',
    'meds.purpose.digestive': 'Sokongan kesihatan pencernaan',
    'meds.purpose.general': 'Sokongan kesihatan umum',
    'meds.status.ongoing': 'Sedang Berjalan',
    'meds.status.completed': 'Selesai',
    'meds.status.upcoming': 'Akan Datang',
    'meds.delivery.scheduled': 'Dijadualkan untuk penghantaran ke rumah',
    'meds.delivery.ready': 'Sedia untuk diambil',
    'meds.delivery.shipped': 'Dalam perjalanan',
    'meds.delivery.delivered': 'Telah dihantar',
    'meds.prescriber.polyclinic': 'Ditetapkan oleh doktor Poliklinik',
    'meds.prescriber.hospital': 'Ditetapkan oleh Pakar Hospital',
    'meds.deliveryTitle': 'Pilihan Penghantaran',
    'meds.deliveryInfo': 'Ubat dari telekonsultasi boleh dihantar ke rumah anda.',
    'meds.delivery.home': 'Penghantaran ke Rumah',
    'meds.delivery.clinic': 'Ambil di Klinik',
    'meds.paymentTitle': 'Pilihan Pembayaran',
    'meds.payment.card': 'Pembayaran Kad',
    'meds.payment.bill': 'Bayar Kemudian',
    'meds.payment.billDesc': 'Bil dihantar untuk pembayaran tunai',
    'meds.disclaimer': 'Maklumat ubat yang ditunjukkan di sini adalah untuk rujukan sahaja. Sila ikut arahan yang diberikan oleh doktor atau ahli farmasi anda.',
    'meds.selectClinic': 'Pilih Klinik Pengambilan',
    'meds.orderSummary': 'Ringkasan Pesanan',
    'meds.subtotal': 'Jumlah Kecil',
    'meds.chasSubsidy': 'Subsidi CHAS',
    'meds.deliveryFee': 'Yuran Penghantaran',
    'meds.selfCollection': 'Pengambilan Sendiri',
    'meds.free': 'PERCUMA',
    'meds.total': 'Jumlah',
    'meds.cardPayment': 'Pembayaran Kad',
    'meds.cardNumber': 'Nombor Kad',
    'meds.cardHolder': 'Nama Pemegang Kad',
    'meds.expiryDate': 'Tarikh Luput',
    'meds.totalAmount': 'Jumlah Keseluruhan',
    'meds.processing': 'Memproses Pembayaran...',
    'meds.payConfirm': 'Bayar & Sahkan Pesanan',
    'meds.securePayment': 'Pembayaran anda dilindungi dengan penyulitan SSL',
    'meds.billCash': 'Bil ke Rumah (Bayaran Tunai)',
    'meds.billDeliveryTitle': 'Penghantaran Bil Pembayaran',
    'meds.billDeliveryInfo': 'Bil pembayaran akan dihantar bersama ubat anda. Bayar secara tunai apabila ia tiba.',
    'meds.billClinicInfo': 'Bayar di kaunter klinik semasa mengambil ubat anda.',
    'meds.fullName': 'Nama Penuh',
    'meds.blockNo': 'No. Blok/Rumah',
    'meds.unitNo': 'No. Unit',
    'meds.street': 'Nama Jalan',
    'meds.postalCode': 'Poskod',
    'meds.amountDue': 'Jumlah Perlu Dibayar (Bayar Kemudian)',
    'meds.confirming': 'Mengesahkan...',
    'meds.confirmOrder': 'Sahkan Pesanan',
    'meds.agreePayBill': 'Dengan meneruskan, anda bersetuju untuk membayar apabila pesanan tiba.',
    'meds.collectAt': 'Ambil di klinik yang dipilih',
    'meds.clinicAddress': 'Sila bawa kad IC/CHAS anda',
    'meds.orderPlaced': 'Pesanan Berjaya Dibuat',
    'meds.orderPlacedDesc': 'Pesanan ubat anda telah disahkan.',
    'meds.continuePayment': 'Teruskan ke Pembayaran',
    'meds.step1': 'Pilih Ubat',
    'meds.step2': 'Penghantaran & Pembayaran',
    'meds.step3': 'Pengesahan',
    'meds.statusUpdate': 'Status Penghantaran Dikemaskini',
    
    'health.title': 'Pemeriksaan Kesihatan',
    'health.bp': 'Tekanan Darah',
    'health.bp.desc': 'Ukur tekanan darah anda',
    'health.weight': 'Tinggi & Berat',
    'health.weight.desc': 'Rekod ukuran anda',
    'health.back': 'Kembali ke Menu',
    'health.result': 'Keputusan Anda',
    'health.normal': 'Normal',
    'health.date': 'Diukur pada',
    'health.pastResults': 'Keputusan Lepas',
    'health.recommendedForYou': 'Disyorkan Untuk Anda',
    'health.basedOnScreening': 'Berdasarkan pemeriksaan kesihatan anda',
    'health.findingProgrammes': 'Mencari program untuk anda...',
    'health.analyzingResults': 'Menganalisis keputusan kesihatan anda',
    'health.recommendationError': 'Tidak dapat memuatkan cadangan',
    'health.viewAllProgrammes': 'Lihat Semua Program',
    'health.saved': 'Keputusan berjaya disimpan',
    'health.saveFailed': 'Gagal menyimpan keputusan',
    
    'teleconsult.title': 'Telekonsultasi',
    'teleconsult.subtitle': 'Berbual dengan doktor dari rumah',
    'teleconsult.polyclinic': 'Doktor Poliklinik',
    'teleconsult.hospital': 'Pakar Hospital',
    'teleconsult.serious': 'Untuk keadaan serius, sila kunjungi poliklinik atau hospital secara peribadi.',
    'teleconsult.payment': 'Pilihan Pembayaran',
    'teleconsult.card': 'Bayar dengan Kad',
    'teleconsult.cash': 'Bil ke Rumah (Tunai)',
    'teleconsult.start': 'Mula Konsultasi',
    'teleconsult.connecting': 'Menyambung kepada doktor...',
    'teleconsult.connected': 'Konsultasi Dimulakan',
    'teleconsult.connected.desc': 'Konsultasi video anda telah dibuka dalam tab pelayar baharu.',
    'teleconsult.failed': 'Sambungan Gagal',
    'teleconsult.failed.desc': 'Tidak dapat memulakan telekonsultasi. Sila cuba lagi.',
    'teleconsult.tryAgain': 'Cuba Lagi',
    'teleconsult.goBack': 'Kembali',
    'teleconsult.returnDashboard': 'Kembali ke Papan Pemuka',
    'teleconsult.selectType': 'Pilih Jenis Konsultasi',
    'teleconsult.continuePayment': 'Teruskan ke Pembayaran',
    'teleconsult.payByCard': 'Bayar dengan Kad',
    'teleconsult.billHome': 'Bil ke Rumah',
    'teleconsult.cardPayment': 'Pembayaran Kad',
    'teleconsult.cardNumber': 'Nombor Kad',
    'teleconsult.cardHolder': 'Nama Pemegang Kad',
    'teleconsult.expiry': 'Tarikh Luput',
    'teleconsult.totalAmount': 'Jumlah Keseluruhan',
    'teleconsult.processing': 'Memproses Pembayaran...',
    'teleconsult.payStart': 'Bayar & Mula Konsultasi',
    'teleconsult.securePayment': 'Pembayaran anda dilindungi dengan penyulitan SSL',
    'teleconsult.billCash': 'Bil ke Rumah (Bayaran Tunai)',
    'teleconsult.billDelivery': 'Penghantaran Bil Pembayaran',
    'teleconsult.billInfo': 'Bil pembayaran akan dihantar ke alamat anda. Bayar secara tunai apabila ia tiba dalam 3-5 hari bekerja.',
    'teleconsult.fullName': 'Nama Penuh',
    'teleconsult.blockNo': 'No. Blok/Rumah',
    'teleconsult.unitNo': 'No. Unit',
    'teleconsult.street': 'Nama Jalan',
    'teleconsult.postalCode': 'Poskod',
    'teleconsult.amountDue': 'Jumlah Perlu Dibayar (Bayar Kemudian)',
    'teleconsult.confirming': 'Mengesahkan...',
    'teleconsult.confirmStart': 'Sahkan & Mula Konsultasi',
    'teleconsult.agreePayBill': 'Dengan meneruskan, anda bersetuju untuk membayar bil apabila ia tiba di alamat anda.',
    'teleconsult.consultFee': 'Yuran Konsultasi',
    'teleconsult.free': 'PERCUMA',
    'teleconsult.subsidisedRate': 'Kadar subsidi untuk pemegang kad {cardType}',
    'teleconsult.polyclinicDoctor': 'Doktor Poliklinik',
    'teleconsult.hospitalSpecialist': 'Pakar Hospital',
    
    'community.title': 'Program Komuniti',
    'community.subtitle': 'Sertai aktiviti berdekatan anda',
    'community.upcoming': 'Acara Akan Datang',
    'community.past': 'Acara Lepas',
    'community.signup': 'Daftar Minat',
    'community.signed': 'Telah Daftar',
    'community.reviews': 'Ulasan',
    'community.points': 'mata',
    'community.filterAll': 'Semua',
    'community.filterActive': 'Senaman',
    'community.filterHealth': 'Ceramah Kesihatan',
    'community.filterSocial': 'Sosial',
    'community.filterCaregiver': 'Penjaga',
    'community.filterDigital': 'Digital',
    'community.programmesFound': 'program dijumpai',
    'community.clearFilter': 'Padam penapis',
    'community.noProgrammes': 'Tiada program dijumpai',
    'community.noCompletedProgrammes': 'Tiada program selesai lagi',
    'community.spotsLeft': 'tempat lagi',
    'community.fullCapacity': 'Penuh',
    'community.moreDetails': 'Maklumat lanjut',
    'community.eligibility': 'Siapa boleh sertai',
    'community.learningObjectives': 'Apa yang akan anda pelajari',
    'community.conductedBy': 'Dikendalikan oleh',
    'community.howToJoin': 'Cara menyertai',
    'community.registerOnline': 'Daftar dalam talian menggunakan borang di bawah',
    'community.callToBook': 'Hubungi untuk tempah',
    'community.walkInWelcome': 'Walk-in dialu-alukan, tiada tempahan diperlukan',
    'community.lastUpdated': 'Kemaskini terakhir',
    'community.quarterlyReview': 'Program disemak dan dikemaskini setiap 3 bulan.',
    'community.programmeNote': 'Maklumat program disemak dan dikemaskini setiap suku tahun oleh pentadbir Rangkaian Penjagaan Komuniti.',
    'community.signupFor': 'Daftar Minat',
    'community.yourName': 'Nama Anda',
    'community.enterName': 'Masukkan nama anda',
    'community.phoneNumber': 'Nombor Telefon',
    'community.confirmSignup': 'Sahkan Pendaftaran',
    'community.submitting': 'Menghantar...',
    'community.callToRegister': 'Sila hubungi untuk mendaftar program ini:',
    'community.walkinInfo': 'Tiada pendaftaran diperlukan. Datang sahaja pada hari tersebut!',
    'community.signupSuccess': 'Pendaftaran berjaya!',
    'community.seeYouThere': 'Kami menantikan kehadiran anda.',
    'community.signupFailed': 'Pendaftaran gagal. Sila cuba lagi.',
    'community.fillAllFields': 'Sila isi semua ruangan',
    'community.invalidPhone': 'Sila masukkan nombor telefon Singapura yang sah',
    'community.feedbackTitle': 'Maklum Balas Ringkas',
    'community.wasHelpful': 'Adakah maklumat ini membantu?',
    'community.optionalComment': 'Sebarang komen? (Pilihan)',
    'community.commentPlaceholder': 'Beritahu kami pendapat anda...',
    'community.submitFeedback': 'Hantar Maklum Balas',
    'community.feedbackThanks': 'Terima kasih atas maklum balas anda!',
    'community.feedbackSubmitted': 'Maklum balas anda membantu kami meningkatkan perkhidmatan.',
    'community.voiceRecorded': 'Suara berjaya dirakam',
    'community.speakNow': 'Sila bercakap sekarang...',
    'community.tapToSpeak': 'Ketuk untuk bercakap',
    'community.tapToStop': '🔴 Merakam... Ketuk butang untuk berhenti',
    'community.voiceHint': 'Ketuk mikrofon untuk menyuarakan maklum balas anda',
    'community.cancel': 'Batal',
    'community.cancelSuccess': 'Penyertaan berjaya dibatalkan',
    'community.cancelError': 'Gagal membatalkan. Sila cuba lagi.',
    'community.yourProgrammes': 'Program Anda',
    'community.allProgrammes': 'Semua Program',
    'community.contactOrganiser': 'Hubungi Penganjur',
    'community.caregiverWelcome': 'Penjaga Dialu-alukan',
    'community.bringFriend': 'Bawa Rakan',
    'community.thankyouRegistering': 'Terima kasih kerana mendaftar minat anda.',
    'community.organiserContact': 'Penganjur akan menghubungi anda jika perlu.',
    'community.onlineProgramme': 'Program Dalam Talian',
    'community.joinOnline': 'Sertai Mesyuarat',
    'community.needDirections': 'Perlukan arah ke lokasi?',
    'community.printGuide': 'Cetak Panduan Perjalanan',
    'community.printing': 'Mencetak...',
    'community.printed': 'Panduan Dicetak!',
    'community.printSuccess': 'Panduan arah berjaya dicetak!',
    'community.close': 'Tutup',
    'community.completedProgrammes': 'Program Selesai',
    'community.completedProgrammesDesc': 'Lihat acara lepas dan tinggalkan ulasan',
    'community.deleteFeedback': 'Padam Maklum Balas?',
    'community.deleteFeedbackConfirm': 'Ini akan memadamkan maklum balas anda secara kekal. Tindakan ini tidak boleh dibatalkan.',
    'community.feedbackDeleted': 'Maklum balas dipadamkan',
    'community.feedbackDeleteError': 'Gagal memadamkan maklum balas',
    'community.updateFeedback': 'Kemas Kini Maklum Balas',
    'community.feedbackUpdated': 'Maklum balas dikemas kini',
    'community.tapToView': 'Ketik untuk lihat',
    'community.eventsAttended': 'acara dihadiri',
    'community.you': 'Anda',
    'common.delete': 'Padam',
    
    'profile.title': 'Profil Saya',
    'profile.chas': 'Jenis Kad CHAS',
    'profile.points': 'Jumlah Mata',
    'profile.history': 'Sejarah Penyertaan',
    'profile.rewards': 'Tebus Ganjaran',
    'profile.redeemRewards': 'Tebus Ganjaran',
    'profile.voucher': 'Baucar',
    'profile.redeem': 'Tebus',
    'profile.quantity': 'Kuantiti',
    'profile.perVoucher': 'setiap baucar',
    'profile.totalPoints': 'Jumlah mata diperlukan',
    'profile.needMorePoints': 'Perlukan {points} lagi mata',
    'profile.noHistory': 'Tiada sejarah penyertaan lagi',
    'profile.joinProgrammes': 'Sertai program komuniti untuk dapatkan mata!',
    'profile.deliveryAddress': 'Alamat Penghantaran',
    'profile.enterAddress': 'Masukkan alamat anda untuk penghantaran ganjaran:',
    'profile.pointsDeduct': 'Mata akan ditolak',
    'profile.confirmRedeem': 'Sahkan & Tebus',
    'profile.processing': 'Memproses...',
    'profile.rewardRedeemed': 'Ganjaran Ditebus!',
    'profile.willBeSent': 'akan dihantar ke rumah anda.',
    'profile.notEnoughPoints': 'Mata tidak mencukupi',
    'profile.fillAddress': 'Sila isi alamat anda',
    'profile.needAddress': 'Kami perlukan alamat anda untuk menghantar ganjaran.',
    'profile.redemptionFailed': 'Penebusan Gagal',
    'profile.tryAgainLater': 'Sila cuba lagi kemudian.',
    'profile.eventsAttended': 'Acara Dihadiri',
    'profile.progressToTier': 'Kemajuan ke Tahap',
    'profile.allTiersUnlocked': 'Semua tahap dibuka!',
    'profile.tierLocked': 'Tahap Dikunci',
    'profile.attendMoreEvents': 'Hadiri acara untuk membuka. Diperlukan:',
    'profile.eventsRequired': 'acara diperlukan',
    'profile.equipped': 'Dilengkapi',
    'profile.unequipMedal': 'Tanggalkan Pingat',
    'profile.print': 'Cetak',
    'profile.maxedOut': 'Had Ditebus',
    'profile.trophyRack': 'Rak Trofi',
    'profile.tapToEquip': 'Ketik untuk lengkapi',
    'profile.remaining': 'baki',
    'profile.maxQuantity': 'Had',
    'profile.browseProgrammes': 'Layari Program',
    'profile.historySubtitle': 'Ganjaran dan pencapaian anda',
    'profile.certificates': 'Sijil',
    'profile.dailyBonusRule': 'Dapatkan 5 mata setiap hari! Bonus log masuk ditetapkan semula pada 12 tengah malam.',
    'profile.dailyBonusClaimed': 'Bonus Harian Dituntut!',
    'profile.dailyBonusDesc': 'Anda mendapat 5 mata bonus kerana log masuk hari ini.',
    
    'access.translate': 'Terjemah',
    'access.voice': 'Panduan Suara',
    'access.voiceOn': 'Suara Hidup',
    'access.voiceOff': 'Suara Mati',
    
    'common.back': 'Kembali',
    'common.next': 'Seterusnya',
    'common.done': 'Selesai',
    'common.cancel': 'Batal',
    'common.confirm': 'Sahkan',
    'common.logout': 'Log Keluar',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
  },
  ta: {
    'scan.title': 'வரவேற்கிறோம்',
    'scan.subtitle': 'தொடர உங்கள் IC / CHAS அட்டையை ஸ்கேன் செய்யவும்',
    'scan.instruction': 'உங்கள் அட்டையை ஸ்கேனரில் வைக்கவும்',
    'scan.scanning': 'ஸ்கேன் செய்கிறது...',
    'scan.success': 'ஸ்கேன் வெற்றி!',
    'scan.loading': 'உங்கள் சுயவிவரத்தை ஏற்றுகிறது...',
    
    'lang.title': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    'lang.subtitle': 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    
    'dashboard.welcome': 'வரவேற்கிறோம்',
    'dashboard.title': 'இன்று நாங்கள் உங்களுக்கு எவ்வாறு உதவ முடியும்?',
    'dashboard.health': 'சுகாதார பரிசோதனைகள்',
    'dashboard.health.desc': 'இரத்த அழுத்தம், உயரம் & எடையை சரிபார்க்கவும்',
    'dashboard.findcare': 'சிகிச்சையைக் கண்டறியவும்',
    'dashboard.findcare.desc': 'அருகிலுள்ள CHAS கிளினிக்குகளைக் கண்டறியவும்',
    'dashboard.community': 'சமூக திட்டங்கள்',
    'dashboard.community.desc': 'சுகாதார பேச்சுக்கள் & செயல்பாடுகளில் சேரவும்',
    'dashboard.profile': 'எனது சுயவிவரம்',
    'dashboard.profile.desc': 'உங்கள் புள்ளிகள் & வெகுமதிகளைப் பார்க்கவும்',
    'dashboard.medications': 'உங்கள் மருந்துகள்',
    'dashboard.medications.desc': 'பரிந்துரைக்கப்பட்ட மருந்துகளைப் பார்க்கவும்',
    
    // Find Care - CCN Framing
    'findcare.title': 'உங்களுக்கு அருகில் சமூக பராமரிப்பு',
    'findcare.titleSubtext': 'சமூக பராமரிப்பு வலையமைப்பு – சிங்கப்பூர்',
    'findcare.subtitle': 'உங்கள் அக்கம்பக்கத்தில் பராமரிப்பு மற்றும் ஆதரவு சேவைகளைக் கண்டறியுங்கள்',
    'findcare.ccnIntro1': 'சமூக பராமரிப்பு வலையமைப்பு முதியோர் மற்றும் பராமரிப்பாளர்களுக்கு வீட்டிற்கு அருகில் பராமரிப்பு சேவைகளைக் கண்டறிய உதவுகிறது.',
    'findcare.ccnIntro2': 'சமூக அடிப்படையிலான பராமரிப்பு வீட்டிற்கு அருகில், அக்கம்பக்கத்தில் முன்கூட்டியே உதவி பெற உதவுகிறது.',
    'findcare.howItWorks': 'சமூக பராமரிப்பு எவ்வாறு செயல்படுகிறது',
    'findcare.howItWorks1': 'சமூக கிளினிக்குகள் மற்றும் பாலிகிளினிக்குகள் பொதுவாக முதல் பராமரிப்பு புள்ளியாகும்',
    'findcare.howItWorks2': 'மருத்துவமனைகள் நிபுணர் அல்லது அவசர பராமரிப்புக்கானவை',
    'findcare.howItWorks3': 'முன்கூட்டிய சமூக ஆதரவு முதியோர் சுதந்திரமாக இருக்க உதவுகிறது',
    'findcare.gpLabel': 'சமூக ஜிபி (முதன்மை பராமரிப்பு)',
    'findcare.polyclinicLabel': 'பாலிகிளினிக் (சமூக பராமரிப்பு)',
    'findcare.hospitalLabel': 'மருத்துவமனை (நிபுணர் பராமரிப்பு)',
    'findcare.partOfCommunity': 'சமூக பராமரிப்பின் ஒரு பகுதி',
    'findcare.ccnNudge': 'அவசரமில்லாத நிலைகளுக்கு சமூக பராமரிப்பு பெரும்பாலும் சிறந்த முதல் படியாகும்.',
    'findcare.helpCloser': 'உதவி நீங்கள் நினைப்பதை விட நெருக்கமாக உள்ளது.',
    'findcare.whyMatters': 'சமூக பராமரிப்பு ஏன் முக்கியம்',
    'findcare.whyMattersText': 'சமூக பராமரிப்பு வலையமைப்பு சேவைகள் முதியோர் மற்றும் பராமரிப்பாளர்களுக்கு முன்கூட்டியே ஆதரவு பெற, தேவையற்ற மருத்துவமனை வருகைகளைக் குறைக்க, வீட்டிற்கு அருகில் பராமரிப்பு பெற உதவுகின்றன.',
    'findcare.ccnFooter': 'இந்த பக்கம் சிங்கப்பூரில் சமூக அடிப்படையிலான பராமரிப்பு விருப்பங்களை புரிந்துகொள்ள உதவுவதன் மூலம் சமூக பராமரிப்பு வலையமைப்பு விழிப்புணர்வை ஆதரிக்கிறது.',
    'findcare.all': 'அனைத்தும்',
    'findcare.polyclinics': 'பாலிகிளினிக்குகள்',
    'findcare.hospitals': 'மருத்துவமனைகள்',
    'findcare.gpClinic': 'ஜிபி கிளினிக்',
    'findcare.dentalClinic': 'பல் மருத்துவம்',
    'findcare.polyclinic': 'பாலிகிளினிக்',
    'findcare.hospital': 'மருத்துவமனை',
    'findcare.call': 'அழைப்பு',
    'findcare.directions': 'வழிகாட்டல் பெறவும்',
    'findcare.emergencyTitle': 'அவசர நிலைக்கு:',
    'findcare.emergencyDesc': 'ஆம்புலன்ஸுக்கு 995 அழைக்கவும் அல்லது அருகிலுள்ள A&E க்கு செல்லவும்.',
    'findcare.call995': '995 அழைக்கவும்',
    'findcare.searchPlaceholder': 'பெயர், முகவரி அல்லது அஞ்சல் குறியீட்டால் தேடவும்',
    'findcare.allRegions': 'அனைத்து பகுதிகள்',
    'findcare.resultsCount': '{count} கிளினிக்குகள் கண்டுபிடிக்கப்பட்டன',
    'findcare.noResults': 'உங்கள் தேடலுக்கு பொருந்தும் கிளினிக்குகள் இல்லை',
    'findcare.chasNoticeTitle': 'CHAS மானியங்கள்:',
    'findcare.chasNoticeDesc': 'மானிய சுகாதார சேவைகளைப் பெற இந்த கிளினிக்குகளில் உங்கள் CHAS அட்டையைக் காட்டவும்.',
    'findcare.mapView': 'வரைபடம்',
    'findcare.listView': 'பட்டியல்',
    'findcare.distance': 'தூரம்',
    'findcare.nearbyClinics': 'அருகிலுள்ள கிளினிக்குகள்',
    'findcare.within': 'உள்',
    'findcare.km': 'கி.மீ',
    'findcare.kmAway': 'கி.மீ தூரத்தில்',
    'findcare.clinicsFound': 'கிளினிக்குகள்',
    'findcare.loading': 'ஏற்றுகிறது...',
    'findcare.loadingClinics': 'கிளினிக்குகளை ஏற்றுகிறது...',
    'findcare.located': 'கண்டறியப்பட்டது',
    'findcare.findMe': 'என்னைக் கண்டுபிடி',
    'findcare.recenter': 'மறுமையப்படுத்து',
    'findcare.clinicTypes': 'கிளினிக் வகைகள்',
    'findcare.yourLocation': 'உங்கள் இடம்',
    'findcare.viewHours': 'நேரத்தைக் காண்க',
    'findcare.openingHours': 'திறக்கும் நேரம்',
    'findcare.fetchHours': 'நேரத்தைப் பெறு',
    'findcare.gp': 'ஜிபி',
    'findcare.dental': 'பல்',
    'findcare.contactNumber': 'தொடர்பு எண்',
    'findcare.callNow': 'இப்போது அழைக்கவும்',
    
    // Medications
    'meds.title': 'உங்கள் மருந்துகள்',
    'meds.yourMeds': 'பரிந்துரைக்கப்பட்ட மருந்துகள்',
    'meds.pastMeds': 'கடந்த மருந்துகள்',
    'meds.pastMedsDesc': 'உங்கள் நடைபெறும் மற்றும் நிறைவடைந்த மருந்துச்சீட்டுகள்',
    'meds.orderMeds': 'மருந்துகளை ஆர்டர் செய்யவும்',
    'meds.orderMedsDesc': 'மீண்டும் ஆர்டர் செய்ய மருந்துகளைத் தேர்ந்தெடுக்கவும்',
    'meds.lastOrder': 'கடைசி ஆர்டர்',
    'meds.perBox': 'ஒரு பெட்டிக்கு',
    'meds.tablets': 'மாத்திரைகள்',
    'meds.purpose.bp': 'இரத்த அழுத்த மேலாண்மை',
    'meds.purpose.chronic': 'நாள்பட்ட நோய் ஆதரவு',
    'meds.purpose.digestive': 'செரிமான ஆரோக்கிய ஆதரவு',
    'meds.purpose.general': 'பொது ஆரோக்கிய ஆதரவு',
    'meds.status.ongoing': 'நடைபெற்றுக்கொண்டிருக்கிறது',
    'meds.status.completed': 'நிறைவடைந்தது',
    'meds.status.upcoming': 'வரவிருக்கிறது',
    'meds.delivery.scheduled': 'வீட்டிற்கு டெலிவரி திட்டமிடப்பட்டது',
    'meds.delivery.ready': 'சேகரிக்க தயாராக உள்ளது',
    'meds.delivery.shipped': 'வழியில் உள்ளது',
    'meds.delivery.delivered': 'டெலிவரி செய்யப்பட்டது',
    'meds.prescriber.polyclinic': 'பாலிகிளினிக் மருத்துவரால் பரிந்துரைக்கப்பட்டது',
    'meds.prescriber.hospital': 'மருத்துவமனை நிபுணரால் பரிந்துரைக்கப்பட்டது',
    'meds.deliveryTitle': 'டெலிவரி விருப்பங்கள்',
    'meds.deliveryInfo': 'தொலை ஆலோசனை மருந்துகள் உங்கள் வீட்டிற்கு டெலிவரி செய்யப்படலாம்.',
    'meds.delivery.home': 'வீட்டிற்கு டெலிவரி',
    'meds.delivery.clinic': 'கிளினிக்கில் சேகரிக்கவும்',
    'meds.paymentTitle': 'கட்டண விருப்பங்கள்',
    'meds.payment.card': 'அட்டை கட்டணம்',
    'meds.payment.bill': 'பின்னர் செலுத்தவும்',
    'meds.payment.billDesc': 'பணம் செலுத்த பில் டெலிவரி செய்யப்படும்',
    'meds.disclaimer': 'இங்கு காட்டப்படும் மருந்து தகவல் குறிப்புக்கு மட்டுமே. உங்கள் மருத்துவர் அல்லது மருந்தாளரின் வழிமுறைகளைப் பின்பற்றவும்.',
    'meds.selectClinic': 'சேகரிப்பு கிளினிக் தேர்ந்தெடுக்கவும்',
    'meds.orderSummary': 'ஆர்டர் சுருக்கம்',
    'meds.subtotal': 'துணை மொத்தம்',
    'meds.chasSubsidy': 'CHAS மானியம்',
    'meds.deliveryFee': 'டெலிவரி கட்டணம்',
    'meds.selfCollection': 'சுய சேகரிப்பு',
    'meds.free': 'இலவசம்',
    'meds.total': 'மொத்தம்',
    'meds.cardPayment': 'அட்டை கட்டணம்',
    'meds.cardNumber': 'அட்டை எண்',
    'meds.cardHolder': 'அட்டை வைத்திருப்பவர் பெயர்',
    'meds.expiryDate': 'காலாவதி தேதி',
    'meds.totalAmount': 'மொத்த தொகை',
    'meds.processing': 'கட்டணம் செயலாக்கப்படுகிறது...',
    'meds.payConfirm': 'செலுத்தி ஆர்டரை உறுதிப்படுத்தவும்',
    'meds.securePayment': 'உங்கள் கட்டணம் SSL குறியாக்கத்துடன் பாதுகாக்கப்படுகிறது',
    'meds.billCash': 'வீட்டிற்கு பில் (பண கட்டணம்)',
    'meds.billDeliveryTitle': 'கட்டண பில் டெலிவரி',
    'meds.billDeliveryInfo': 'கட்டண பில் உங்கள் மருந்துகளுடன் அனுப்பப்படும். வரும்போது பணமாக செலுத்தவும்.',
    'meds.billClinicInfo': 'உங்கள் மருந்துகளை சேகரிக்கும் போது கிளினிக் கவுண்டரில் செலுத்தவும்.',
    'meds.fullName': 'முழு பெயர்',
    'meds.blockNo': 'பிளாக்/வீட்டு எண்',
    'meds.unitNo': 'யூனிட் எண்',
    'meds.street': 'தெரு பெயர்',
    'meds.postalCode': 'அஞ்சல் குறியீடு',
    'meds.amountDue': 'செலுத்த வேண்டிய தொகை (பின்னர் செலுத்தவும்)',
    'meds.confirming': 'உறுதிப்படுத்துகிறது...',
    'meds.confirmOrder': 'ஆர்டரை உறுதிப்படுத்தவும்',
    'meds.agreePayBill': 'தொடர்வதன் மூலம், ஆர்டர் வரும்போது செலுத்த ஒப்புக்கொள்கிறீர்கள்.',
    'meds.collectAt': 'தேர்ந்தெடுக்கப்பட்ட கிளினிக்கில் சேகரிக்கவும்',
    'meds.clinicAddress': 'உங்கள் IC/CHAS அட்டையை கொண்டு வரவும்',
    'meds.orderPlaced': 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது',
    'meds.orderPlacedDesc': 'உங்கள் மருந்து ஆர்டர் உறுதிப்படுத்தப்பட்டது.',
    'meds.continuePayment': 'கட்டணத்திற்கு தொடரவும்',
    'meds.step1': 'மருந்துகளைத் தேர்ந்தெடுக்கவும்',
    'meds.step2': 'டெலிவரி & கட்டணம்',
    'meds.step3': 'உறுதிப்படுத்தல்',
    'meds.statusUpdate': 'டெலிவரி நிலை புதுப்பிக்கப்பட்டது',
    
    'health.title': 'சுகாதார பரிசோதனைகள்',
    'health.bp': 'இரத்த அழுத்தம்',
    'health.bp.desc': 'உங்கள் இரத்த அழுத்தத்தை அளவிடுங்கள்',
    'health.weight': 'உயரம் & எடை',
    'health.weight.desc': 'உங்கள் அளவீடுகளை பதிவு செய்யுங்கள்',
    'health.back': 'மெனுவிற்கு திரும்பு',
    'health.result': 'உங்கள் முடிவு',
    'health.normal': 'சாதாரண',
    'health.date': 'அளவிடப்பட்ட தேதி',
    'health.pastResults': 'கடந்த முடிவுகள்',
    'health.recommendedForYou': 'உங்களுக்கு பரிந்துரைக்கப்பட்டது',
    'health.basedOnScreening': 'உங்கள் உடல்நலப் பரிசோதனையின் அடிப்படையில்',
    'health.findingProgrammes': 'உங்களுக்கான திட்டங்களைக் கண்டறிகிறது...',
    'health.analyzingResults': 'உங்கள் உடல்நல முடிவுகளை பகுப்பாய்வு செய்கிறது',
    'health.recommendationError': 'பரிந்துரைகளை ஏற்ற முடியவில்லை',
    'health.viewAllProgrammes': 'அனைத்து திட்டங்களையும் காண்க',
    'health.saved': 'முடிவு வெற்றிகரமாக சேமிக்கப்பட்டது',
    'health.saveFailed': 'முடிவை சேமிக்க முடியவில்லை',
    
    'teleconsult.title': 'தொலை ஆலோசனை',
    'teleconsult.subtitle': 'வீட்டிலிருந்தே மருத்துவரிடம் பேசுங்கள்',
    'teleconsult.polyclinic': 'பாலிகிளினிக் மருத்துவர்',
    'teleconsult.hospital': 'மருத்துவமனை நிபுணர்',
    'teleconsult.serious': 'தீவிர நிலைகளுக்கு, நேரில் பாலிகிளினிக் அல்லது மருத்துவமனைக்கு செல்லவும்.',
    'teleconsult.payment': 'கட்டண விருப்பங்கள்',
    'teleconsult.card': 'அட்டையில் செலுத்து',
    'teleconsult.cash': 'வீட்டிற்கு பில் (பணம்)',
    'teleconsult.start': 'ஆலோசனையைத் தொடங்கு',
    'teleconsult.connecting': 'மருத்துவருடன் இணைக்கிறது...',
    'teleconsult.connected': 'ஆலோசனை தொடங்கியது',
    'teleconsult.connected.desc': 'உங்கள் வீடியோ ஆலோசனை புதிய உலாவி தாவலில் திறக்கப்பட்டது.',
    'teleconsult.failed': 'இணைப்பு தோல்வி',
    'teleconsult.failed.desc': 'தொலை ஆலோசனையைத் தொடங்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'teleconsult.tryAgain': 'மீண்டும் முயற்சி',
    'teleconsult.goBack': 'பின்செல்',
    'teleconsult.returnDashboard': 'டாஷ்போர்டுக்கு திரும்பு',
    'teleconsult.selectType': 'ஆலோசனை வகையைத் தேர்ந்தெடுக்கவும்',
    'teleconsult.continuePayment': 'கட்டணத்திற்கு தொடரவும்',
    'teleconsult.payByCard': 'அட்டையில் செலுத்து',
    'teleconsult.billHome': 'வீட்டிற்கு பில்',
    'teleconsult.cardPayment': 'அட்டை கட்டணம்',
    'teleconsult.cardNumber': 'அட்டை எண்',
    'teleconsult.cardHolder': 'அட்டை உரிமையாளர் பெயர்',
    'teleconsult.expiry': 'காலாவதி தேதி',
    'teleconsult.totalAmount': 'மொத்த தொகை',
    'teleconsult.processing': 'கட்டணம் செயலாக்கப்படுகிறது...',
    'teleconsult.payStart': 'செலுத்தி ஆலோசனையைத் தொடங்கு',
    'teleconsult.securePayment': 'உங்கள் கட்டணம் SSL குறியாக்கத்தால் பாதுகாக்கப்படுகிறது',
    'teleconsult.billCash': 'வீட்டிற்கு பில் (பண கட்டணம்)',
    'teleconsult.billDelivery': 'கட்டண பில் டெலிவரி',
    'teleconsult.billInfo': 'கட்டண பில் உங்கள் முகவரிக்கு அனுப்பப்படும். 3-5 வேலை நாட்களில் வரும்போது பணமாக செலுத்தவும்.',
    'teleconsult.fullName': 'முழு பெயர்',
    'teleconsult.blockNo': 'தொகுதி/வீட்டு எண்',
    'teleconsult.unitNo': 'அலகு எண்',
    'teleconsult.street': 'தெரு பெயர்',
    'teleconsult.postalCode': 'அஞ்சல் குறியீடு',
    'teleconsult.amountDue': 'செலுத்த வேண்டிய தொகை (பின்னர் செலுத்து)',
    'teleconsult.confirming': 'உறுதிப்படுத்துகிறது...',
    'teleconsult.confirmStart': 'உறுதிப்படுத்தி ஆலோசனையைத் தொடங்கு',
    'teleconsult.agreePayBill': 'தொடர்வதன் மூலம், பில் உங்கள் முகவரியில் வரும்போது செலுத்த ஒப்புக்கொள்கிறீர்கள்.',
    'teleconsult.consultFee': 'ஆலோசனை கட்டணம்',
    'teleconsult.free': 'இலவசம்',
    'teleconsult.subsidisedRate': '{cardType} அட்டை உரிமையாளர்களுக்கான மானிய விலை',
    'teleconsult.polyclinicDoctor': 'பாலிகிளினிக் மருத்துவர்',
    'teleconsult.hospitalSpecialist': 'மருத்துவமனை நிபுணர்',
    
    'community.title': 'சமூக திட்டங்கள்',
    'community.subtitle': 'உங்கள் அருகிலுள்ள நிகழ்ச்சிகளில் சேரவும்',
    'community.upcoming': 'வரவிருக்கும் நிகழ்வுகள்',
    'community.past': 'கடந்த நிகழ்வுகள்',
    'community.signup': 'ஆர்வத்தை பதிவு செய்',
    'community.signed': 'பதிவு செய்யப்பட்டது',
    'community.reviews': 'மதிப்புரைகள்',
    'community.points': 'புள்ளிகள்',
    'community.filterAll': 'அனைத்தும்',
    'community.filterActive': 'உடற்பயிற்சி',
    'community.filterHealth': 'சுகாதார பேச்சுகள்',
    'community.filterSocial': 'சமூக',
    'community.filterCaregiver': 'பராமரிப்பாளர்',
    'community.filterDigital': 'டிஜிட்டல்',
    'community.programmesFound': 'திட்டங்கள் கண்டுபிடிக்கப்பட்டன',
    'community.clearFilter': 'வடிப்பான் அழி',
    'community.noProgrammes': 'திட்டங்கள் எதுவும் இல்லை',
    'community.noCompletedProgrammes': 'முடிந்த திட்டங்கள் இன்னும் இல்லை',
    'community.spotsLeft': 'இடங்கள் மீதமுள்ளன',
    'community.fullCapacity': 'நிரம்பியது',
    'community.moreDetails': 'மேலும் விவரங்கள்',
    'community.eligibility': 'யார் சேரலாம்',
    'community.learningObjectives': 'நீங்கள் என்ன கற்றுக்கொள்வீர்கள்',
    'community.conductedBy': 'நடத்துபவர்',
    'community.howToJoin': 'எப்படி சேர்வது',
    'community.registerOnline': 'கீழே உள்ள படிவத்தைப் பயன்படுத்தி ஆன்லைனில் பதிவு செய்யவும்',
    'community.callToBook': 'முன்பதிவு செய்ய அழைக்கவும்',
    'community.walkInWelcome': 'நேரடியாக வரவேற்கிறோம், முன்பதிவு தேவையில்லை',
    'community.lastUpdated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
    'community.quarterlyReview': 'திட்டங்கள் ஒவ்வொரு 3 மாதங்களுக்கும் மதிப்பாய்வு செய்யப்பட்டு புதுப்பிக்கப்படும்.',
    'community.programmeNote': 'திட்ட தகவல்கள் சமூக பராமரிப்பு வலையமைப்பு நிர்வாகிகளால் காலாண்டுக்கு ஒருமுறை மதிப்பாய்வு செய்யப்பட்டு புதுப்பிக்கப்படுகின்றன.',
    'community.signupFor': 'ஆர்வத்தை பதிவு செய்',
    'community.yourName': 'உங்கள் பெயர்',
    'community.enterName': 'உங்கள் பெயரை உள்ளிடவும்',
    'community.phoneNumber': 'தொலைபேசி எண்',
    'community.confirmSignup': 'பதிவை உறுதிப்படுத்து',
    'community.submitting': 'சமர்ப்பிக்கிறது...',
    'community.callToRegister': 'இந்த திட்டத்தில் பதிவு செய்ய அழைக்கவும்:',
    'community.walkinInfo': 'பதிவு தேவையில்லை. அன்றைய தினம் வாருங்கள்!',
    'community.signupSuccess': 'பதிவு வெற்றி!',
    'community.seeYouThere': 'உங்களைப் பார்க்க காத்திருக்கிறோம்.',
    'community.signupFailed': 'பதிவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    'community.fillAllFields': 'அனைத்து புலங்களையும் நிரப்பவும்',
    'community.invalidPhone': 'சரியான சிங்கப்பூர் தொலைபேசி எண்ணை உள்ளிடவும்',
    'community.feedbackTitle': 'விரைவு கருத்து',
    'community.wasHelpful': 'இந்த தகவல் உதவியாக இருந்ததா?',
    'community.optionalComment': 'ஏதாவது கருத்துகள்? (விருப்பமானது)',
    'community.commentPlaceholder': 'உங்கள் எண்ணங்களைச் சொல்லுங்கள்...',
    'community.submitFeedback': 'கருத்தை சமர்ப்பி',
    'community.feedbackThanks': 'உங்கள் கருத்துக்கு நன்றி!',
    'community.feedbackSubmitted': 'உங்கள் கருத்து எங்கள் சேவைகளை மேம்படுத்த உதவுகிறது.',
    'community.voiceRecorded': 'குரல் வெற்றிகரமாக பதிவு செய்யப்பட்டது',
    'community.speakNow': 'இப்போது பேசுங்கள்...',
    'community.tapToSpeak': 'பேச தட்டவும்',
    'community.tapToStop': '🔴 பதிவு செய்கிறது... நிறுத்த பொத்தானைத் தட்டவும்',
    'community.voiceHint': 'உங்கள் கருத்தைக் கூற மைக்ரோஃபோனைத் தட்டவும்',
    'community.cancel': 'ரத்து செய்',
    'community.cancelSuccess': 'பங்கேற்பு வெற்றிகரமாக ரத்து செய்யப்பட்டது',
    'community.cancelError': 'ரத்து செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'community.yourProgrammes': 'உங்கள் நிகழ்ச்சிகள்',
    'community.allProgrammes': 'அனைத்து நிகழ்ச்சிகள்',
    'community.contactOrganiser': 'ஒருங்கிணைப்பாளரைத் தொடர்பு கொள்ளவும்',
    'community.caregiverWelcome': 'பராமரிப்பாளர் வரவேற்கப்படுகிறார்',
    'community.bringFriend': 'நண்பரை அழைத்து வாருங்கள்',
    'community.thankyouRegistering': 'உங்கள் ஆர்வத்தைப் பதிவு செய்ததற்கு நன்றி.',
    'community.organiserContact': 'தேவைப்பட்டால் ஒருங்கிணைப்பாளர் உங்களைத் தொடர்பு கொள்வார்.',
    'community.onlineProgramme': 'ஆன்லைன் திட்டம்',
    'community.joinOnline': 'கூட்டத்தில் சேர்',
    'community.needDirections': 'இடத்திற்கு வழி வேண்டுமா?',
    'community.printGuide': 'வழிகாட்டி அச்சிடு',
    'community.printing': 'அச்சிடுகிறது...',
    'community.printed': 'வழிகாட்டி அச்சிடப்பட்டது!',
    'community.printSuccess': 'வழிகாட்டி வெற்றிகரமாக அச்சிடப்பட்டது!',
    'community.close': 'மூடு',
    'community.completedProgrammes': 'முடிந்த திட்டங்கள்',
    'community.completedProgrammesDesc': 'கடந்த நிகழ்வுகளைப் பார்த்து மதிப்புரைகள் இடுங்கள்',
    'community.deleteFeedback': 'கருத்தை நீக்கவா?',
    'community.deleteFeedbackConfirm': 'இது உங்கள் கருத்தை நிரந்தரமாக நீக்கும். இந்த செயலை மாற்ற முடியாது.',
    'community.feedbackDeleted': 'கருத்து நீக்கப்பட்டது',
    'community.feedbackDeleteError': 'கருத்தை நீக்க முடியவில்லை',
    'community.updateFeedback': 'கருத்தை புதுப்பி',
    'community.feedbackUpdated': 'கருத்து புதுப்பிக்கப்பட்டது',
    'community.tapToView': 'பார்க்க தட்டவும்',
    'community.eventsAttended': 'நிகழ்வுகள் கலந்துகொண்டது',
    'community.you': 'நீங்கள்',
    'common.delete': 'நீக்கு',
    'profile.title': 'எனது சுயவிவரம்',
    'profile.chas': 'CHAS அட்டை வகை',
    'profile.points': 'மொத்த புள்ளிகள்',
    'profile.history': 'பங்கேற்பு வரலாறு',
    'profile.rewards': 'வெகுமதிகளை பெறுங்கள்',
    'profile.redeemRewards': 'வெகுமதிகளை பெறுங்கள்',
    'profile.voucher': 'வவுச்சர்',
    'profile.redeem': 'பெறு',
    'profile.quantity': 'அளவு',
    'profile.perVoucher': 'ஒவ்வொரு வவுச்சருக்கும்',
    'profile.totalPoints': 'தேவையான மொத்த புள்ளிகள்',
    'profile.needMorePoints': 'இன்னும் {points} புள்ளிகள் தேவை',
    'profile.noHistory': 'இதுவரை பங்கேற்பு இல்லை',
    'profile.joinProgrammes': 'புள்ளிகள் பெற சமூக திட்டங்களில் சேரவும்!',
    'profile.deliveryAddress': 'டெலிவரி முகவரி',
    'profile.enterAddress': 'வெகுமதி டெலிவரிக்கு முகவரியை உள்ளிடவும்:',
    'profile.pointsDeduct': 'கழிக்கப்படும் புள்ளிகள்',
    'profile.confirmRedeem': 'உறுதிப்படுத்தி பெறவும்',
    'profile.processing': 'செயலாக்கப்படுகிறது...',
    'profile.rewardRedeemed': 'வெகுமதி பெறப்பட்டது!',
    'profile.willBeSent': 'உங்கள் வீட்டிற்கு அனுப்பப்படும்.',
    'profile.notEnoughPoints': 'போதுமான புள்ளிகள் இல்லை',
    'profile.fillAddress': 'உங்கள் முகவரியை நிரப்பவும்',
    'profile.needAddress': 'வெகுமதியை டெலிவரி செய்ய உங்கள் முகவரி தேவை.',
    'profile.redemptionFailed': 'பெறுதல் தோல்வி',
    'profile.tryAgainLater': 'பின்னர் மீண்டும் முயற்சிக்கவும்.',
    'profile.eventsAttended': 'கலந்துகொண்ட நிகழ்வுகள்',
    'profile.progressToTier': 'நிலைக்கு முன்னேற்றம்',
    'profile.allTiersUnlocked': 'அனைத்து நிலைகளும் திறக்கப்பட்டன!',
    'profile.tierLocked': 'நிலை பூட்டப்பட்டுள்ளது',
    'profile.attendMoreEvents': 'திறக்க நிகழ்வுகளில் கலந்துகொள்ளுங்கள். தேவை:',
    'profile.eventsRequired': 'நிகழ்வுகள் தேவை',
    'profile.equipped': 'பொருத்தப்பட்டது',
    'profile.unequipMedal': 'பதக்கத்தை அகற்று',
    'profile.print': 'அச்சிடு',
    'profile.maxedOut': 'அதிகபட்சம் பெறப்பட்டது',
    'profile.trophyRack': 'விருது தட்டு',
    'profile.tapToEquip': 'பொருத்த தட்டவும்',
    'profile.remaining': 'மீதமுள்ளது',
    'profile.maxQuantity': 'அதிகபட்சம்',
    'profile.browseProgrammes': 'திட்டங்களை பார்வையிடு',
    'profile.historySubtitle': 'உங்கள் வெகுமதிகள் மற்றும் சாதனைகள்',
    'profile.certificates': 'சான்றிதழ்கள்',
    'profile.dailyBonusRule': 'தினமும் 5 புள்ளிகள் பெறுங்கள்! உள்நுழைவு போனஸ் நள்ளிரவு 12 மணிக்கு மீட்டமைக்கப்படும்.',
    'profile.dailyBonusClaimed': 'தினசரி போனஸ் பெறப்பட்டது!',
    'profile.dailyBonusDesc': 'இன்று உள்நுழைந்ததற்கு 5 போனஸ் புள்ளிகள் பெற்றீர்கள்.',
    
    'access.translate': 'மொழிபெயர்',
    'access.voice': 'குரல் வழிகாட்டி',
    'access.voiceOn': 'குரல் இயக்கம்',
    'access.voiceOff': 'குரல் நிறுத்தம்',
    
    'common.back': 'பின்செல்',
    'common.next': 'அடுத்து',
    'common.done': 'முடிந்தது',
    'common.cancel': 'ரத்து',
    'common.confirm': 'உறுதிப்படுத்து',
    'common.logout': 'வெளியேறு',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
  },
};

const AppContext = createContext<AppContextType | undefined>(undefined);

const SESSION_KEY = 'kiosk_user_session';

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const [user, setUser] = useState<UserProfile | null>(() => {
    // Restore user session from localStorage on initial load
    try {
      const saved = localStorage.getItem(SESSION_KEY);
      if (saved) {
        return JSON.parse(saved) as UserProfile;
      }
    } catch (e) {
      console.error('Failed to restore session:', e);
    }
    return null;
  });
  const [isVoiceEnabled, setIsVoiceEnabled] = useState(false);
  const [isTtsEnabled, setIsTtsEnabled] = useState(true);

  // Persist user session to localStorage whenever it changes
  useEffect(() => {
    if (user) {
      localStorage.setItem(SESSION_KEY, JSON.stringify(user));
    } else {
      localStorage.removeItem(SESSION_KEY);
    }
  }, [user]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <AppContext.Provider
      value={{
        language,
        setLanguage,
        user,
        setUser,
        isVoiceEnabled,
        setIsVoiceEnabled,
        isTtsEnabled,
        setIsTtsEnabled,
        t,
      }}
    >
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}
