import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh' | 'ms' | 'ta';

interface UserProfile {
  id: string;
  name: string;
  nric: string;
  chasType: 'Blue' | 'Orange' | 'Green';
  points: number;
  participationHistory: string[];
}

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  user: UserProfile | null;
  setUser: (user: UserProfile | null) => void;
  isVoiceEnabled: boolean;
  setIsVoiceEnabled: (enabled: boolean) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Scan screen
    'scan.title': 'Welcome',
    'scan.subtitle': 'Please scan your IC / CHAS card to continue',
    'scan.instruction': 'Place your card on the scanner',
    'scan.scanning': 'Scanning...',
    'scan.success': 'Scan successful!',
    'scan.loading': 'Loading your profile...',
    
    // Language selection
    'lang.title': 'Choose Your Language',
    'lang.subtitle': 'Select your preferred language',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.title': 'How can we help you today?',
    'dashboard.health': 'Health Screenings',
    'dashboard.health.desc': 'Check your blood pressure, height & weight',
    'dashboard.teleconsult': 'Teleconsultation',
    'dashboard.teleconsult.desc': 'Speak to a doctor online',
    'dashboard.community': 'Community Programmes',
    'dashboard.community.desc': 'Join health talks & activities',
    'dashboard.profile': 'My Profile',
    'dashboard.profile.desc': 'View your points & rewards',
    'dashboard.medications': 'Your Medications',
    'dashboard.medications.desc': 'View prescribed medications',
    
    // Medications
    'meds.title': 'Your Medications',
    'meds.yourMeds': 'Prescribed Medications',
    'meds.pastMeds': 'Past Medications',
    'meds.pastMedsDesc': 'Your ongoing and completed prescriptions',
    'meds.orderMeds': 'Order Medications',
    'meds.orderMedsDesc': 'Select medications to reorder',
    'meds.lastOrder': 'Last ordered',
    'meds.perBox': 'per box',
    'meds.tablets': 'tablets',
    'meds.purpose.bp': 'Blood pressure management',
    'meds.purpose.chronic': 'Chronic condition support',
    'meds.purpose.digestive': 'Digestive health support',
    'meds.purpose.general': 'General health support',
    'meds.status.ongoing': 'Ongoing',
    'meds.status.completed': 'Completed',
    'meds.status.upcoming': 'Upcoming',
    'meds.delivery.scheduled': 'Scheduled for home delivery',
    'meds.delivery.ready': 'Ready for collection',
    'meds.delivery.shipped': 'On the way',
    'meds.delivery.delivered': 'Delivered',
    'meds.prescriber.polyclinic': 'Prescribed by Polyclinic doctor',
    'meds.prescriber.hospital': 'Prescribed by Hospital specialist',
    'meds.deliveryTitle': 'Delivery Options',
    'meds.deliveryInfo': 'Medications from teleconsultation can be delivered to your home.',
    'meds.delivery.home': 'Home Delivery',
    'meds.delivery.clinic': 'Collect at Clinic',
    'meds.paymentTitle': 'Payment Options',
    'meds.payment.card': 'Card Payment',
    'meds.payment.bill': 'Pay Later',
    'meds.payment.billDesc': 'Bill delivered for cash payment',
    'meds.disclaimer': 'Medication information shown here is for reference only. Please follow instructions given by your doctor or pharmacist.',
    'meds.selectClinic': 'Select Collection Clinic',
    'meds.orderSummary': 'Order Summary',
    'meds.subtotal': 'Subtotal',
    'meds.chasSubsidy': 'CHAS Subsidy',
    'meds.deliveryFee': 'Delivery Fee',
    'meds.selfCollection': 'Self Collection',
    'meds.free': 'FREE',
    'meds.total': 'Total',
    'meds.cardPayment': 'Card Payment',
    'meds.cardNumber': 'Card Number',
    'meds.cardHolder': 'Cardholder Name',
    'meds.expiryDate': 'Expiry Date',
    'meds.totalAmount': 'Total Amount',
    'meds.processing': 'Processing Payment...',
    'meds.payConfirm': 'Pay & Confirm Order',
    'meds.securePayment': 'Your payment is secured with SSL encryption',
    'meds.billCash': 'Bill to Home (Cash Payment)',
    'meds.billDeliveryTitle': 'Payment Bill Delivery',
    'meds.billDeliveryInfo': 'A payment bill will be sent with your medications. Pay in cash when it arrives.',
    'meds.billClinicInfo': 'Pay at the clinic counter when collecting your medications.',
    'meds.fullName': 'Full Name',
    'meds.blockNo': 'Block/House No.',
    'meds.unitNo': 'Unit No.',
    'meds.street': 'Street Name',
    'meds.postalCode': 'Postal Code',
    'meds.amountDue': 'Amount Due (Pay Later)',
    'meds.confirming': 'Confirming...',
    'meds.confirmOrder': 'Confirm Order',
    'meds.agreePayBill': 'By proceeding, you agree to pay when the order arrives.',
    'meds.collectAt': 'Collect at selected clinic',
    'meds.clinicAddress': 'Please bring your IC/CHAS card',
    'meds.orderPlaced': 'Order Placed Successfully',
    'meds.orderPlacedDesc': 'Your medication order has been confirmed.',
    'meds.continuePayment': 'Continue to Payment',
    'meds.step1': 'Select Medications',
    'meds.step2': 'Delivery & Payment',
    'meds.step3': 'Confirmation',
    'meds.statusUpdate': 'Delivery Status Updated',
    
    // Health screenings
    'health.title': 'Health Screenings',
    'health.bp': 'Blood Pressure',
    'health.bp.desc': 'Measure your blood pressure',
    'health.weight': 'Height & Weight',
    'health.weight.desc': 'Record your measurements',
    'health.back': 'Back to Menu',
    'health.result': 'Your Result',
    'health.normal': 'Normal',
    'health.date': 'Measured on',
    'health.pastResults': 'Past Results',
    'health.saved': 'Result saved successfully',
    'health.saveFailed': 'Failed to save result',
    
    // Teleconsult
    'teleconsult.title': 'Teleconsultation',
    'teleconsult.subtitle': 'Speak to a doctor from home',
    'teleconsult.polyclinic': 'Polyclinic Doctor',
    'teleconsult.hospital': 'Hospital Specialist',
    'teleconsult.serious': 'For serious conditions, please visit a polyclinic or hospital in person.',
    'teleconsult.payment': 'Payment Options',
    'teleconsult.card': 'Pay by Card',
    'teleconsult.cash': 'Bill to Home (Cash)',
    'teleconsult.start': 'Start Consultation',
    'teleconsult.connecting': 'Connecting to doctor...',
    'teleconsult.connected': 'Consultation Started',
    'teleconsult.connected.desc': 'Your video consultation has been opened in a new browser tab.',
    'teleconsult.failed': 'Connection Failed',
    'teleconsult.failed.desc': 'Unable to start the teleconsultation. Please try again.',
    'teleconsult.tryAgain': 'Try Again',
    'teleconsult.goBack': 'Go Back',
    'teleconsult.returnDashboard': 'Return to Dashboard',
    'teleconsult.selectType': 'Select Consultation Type',
    'teleconsult.continuePayment': 'Continue to Payment',
    'teleconsult.payByCard': 'Pay by Card',
    'teleconsult.billHome': 'Bill to Home',
    'teleconsult.cardPayment': 'Card Payment',
    'teleconsult.cardNumber': 'Card Number',
    'teleconsult.cardHolder': 'Cardholder Name',
    'teleconsult.expiry': 'Expiry Date',
    'teleconsult.totalAmount': 'Total Amount',
    'teleconsult.processing': 'Processing Payment...',
    'teleconsult.payStart': 'Pay & Start Consultation',
    'teleconsult.securePayment': 'Your payment is secured with SSL encryption',
    'teleconsult.billCash': 'Bill to Home (Cash Payment)',
    'teleconsult.billDelivery': 'Payment Bill Delivery',
    'teleconsult.billInfo': 'A payment bill will be sent to your address. Pay in cash when it arrives within 3-5 working days.',
    'teleconsult.fullName': 'Full Name',
    'teleconsult.blockNo': 'Block/House No.',
    'teleconsult.unitNo': 'Unit No.',
    'teleconsult.street': 'Street Name',
    'teleconsult.postalCode': 'Postal Code',
    'teleconsult.amountDue': 'Amount Due (Pay Later)',
    'teleconsult.confirming': 'Confirming...',
    'teleconsult.confirmStart': 'Confirm & Start Consultation',
    'teleconsult.agreePayBill': 'By proceeding, you agree to pay the bill when it arrives at your address.',
    'teleconsult.consultFee': 'Consultation Fee',
    'teleconsult.free': 'FREE',
    'teleconsult.subsidisedRate': 'Subsidised rate for {cardType} cardholders',
    'teleconsult.polyclinicDoctor': 'Polyclinic Doctor',
    'teleconsult.hospitalSpecialist': 'Hospital Specialist',
    
    // Community
    'community.title': 'Community Programmes',
    'community.upcoming': 'Upcoming Events',
    'community.past': 'Past Events',
    'community.signup': 'Sign Up',
    'community.signed': 'Signed Up',
    'community.reviews': 'Reviews',
    'community.points': 'points',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.chas': 'CHAS Card Type',
    'profile.points': 'Total Points',
    'profile.history': 'Participation History',
    'profile.rewards': 'Redeem Rewards',
    'profile.voucher': 'Voucher',
    'profile.redeem': 'Redeem',
    
    // Accessibility
    'access.translate': 'Translate',
    'access.voice': 'Voice Guide',
    'access.voiceOn': 'Voice On',
    'access.voiceOff': 'Voice Off',
    
    // Common
    'common.back': 'Back',
    'common.next': 'Next',
    'common.done': 'Done',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.logout': 'Log Out',
  },
  zh: {
    'scan.title': '欢迎',
    'scan.subtitle': '请扫描您的身份证/CHAS卡以继续',
    'scan.instruction': '将您的卡放在扫描器上',
    'scan.scanning': '扫描中...',
    'scan.success': '扫描成功！',
    'scan.loading': '正在加载您的资料...',
    
    'lang.title': '选择您的语言',
    'lang.subtitle': '选择您偏好的语言',
    
    'dashboard.welcome': '欢迎',
    'dashboard.title': '今天我们能如何帮助您？',
    'dashboard.health': '健康检查',
    'dashboard.health.desc': '检查血压、身高和体重',
    'dashboard.teleconsult': '远程医疗',
    'dashboard.teleconsult.desc': '在线咨询医生',
    'dashboard.community': '社区活动',
    'dashboard.community.desc': '参加健康讲座和活动',
    'dashboard.profile': '我的资料',
    'dashboard.profile.desc': '查看积分和奖励',
    'dashboard.medications': '您的药物',
    'dashboard.medications.desc': '查看处方药物',
    
    // Medications
    'meds.title': '您的药物',
    'meds.yourMeds': '处方药物',
    'meds.pastMeds': '过往药物',
    'meds.pastMedsDesc': '您正在进行和已完成的处方',
    'meds.orderMeds': '订购药物',
    'meds.orderMedsDesc': '选择要重新订购的药物',
    'meds.lastOrder': '上次订购',
    'meds.perBox': '每盒',
    'meds.tablets': '片',
    'meds.purpose.bp': '血压管理',
    'meds.purpose.chronic': '慢性病支持',
    'meds.purpose.digestive': '消化健康支持',
    'meds.purpose.general': '一般健康支持',
    'meds.status.ongoing': '进行中',
    'meds.status.completed': '已完成',
    'meds.status.upcoming': '即将开始',
    'meds.delivery.scheduled': '已安排送货上门',
    'meds.delivery.ready': '可领取',
    'meds.delivery.shipped': '配送中',
    'meds.delivery.delivered': '已送达',
    'meds.prescriber.polyclinic': '综合诊所医生处方',
    'meds.prescriber.hospital': '医院专科医生处方',
    'meds.deliveryTitle': '配送方式',
    'meds.deliveryInfo': '远程医疗开出的药物可以送到您家。',
    'meds.delivery.home': '送货上门',
    'meds.delivery.clinic': '到诊所领取',
    'meds.paymentTitle': '付款方式',
    'meds.payment.card': '刷卡付款',
    'meds.payment.bill': '稍后付款',
    'meds.payment.billDesc': '账单寄到家现金支付',
    'meds.disclaimer': '此处显示的药物信息仅供参考。请遵循您的医生或药剂师的指示。',
    'meds.selectClinic': '选择领取诊所',
    'meds.orderSummary': '订单摘要',
    'meds.subtotal': '小计',
    'meds.chasSubsidy': 'CHAS补贴',
    'meds.deliveryFee': '配送费',
    'meds.selfCollection': '自取',
    'meds.free': '免费',
    'meds.total': '总计',
    'meds.cardPayment': '刷卡付款',
    'meds.cardNumber': '卡号',
    'meds.cardHolder': '持卡人姓名',
    'meds.expiryDate': '有效期',
    'meds.totalAmount': '总金额',
    'meds.processing': '处理付款中...',
    'meds.payConfirm': '付款并确认订单',
    'meds.securePayment': '您的付款通过SSL加密保护',
    'meds.billCash': '账单寄到家（现金付款）',
    'meds.billDeliveryTitle': '账单寄送',
    'meds.billDeliveryInfo': '账单将与药物一起寄送。收到后现金付款。',
    'meds.billClinicInfo': '在诊所柜台领取药物时付款。',
    'meds.fullName': '全名',
    'meds.blockNo': '门牌号',
    'meds.unitNo': '单位号',
    'meds.street': '街道名称',
    'meds.postalCode': '邮政编码',
    'meds.amountDue': '应付金额（稍后付款）',
    'meds.confirming': '确认中...',
    'meds.confirmOrder': '确认订单',
    'meds.agreePayBill': '继续即表示您同意在收到订单时付款。',
    'meds.collectAt': '在所选诊所领取',
    'meds.clinicAddress': '请携带您的身份证/CHAS卡',
    'meds.orderPlaced': '订单已成功提交',
    'meds.orderPlacedDesc': '您的药物订单已确认。',
    'meds.continuePayment': '继续付款',
    'meds.step1': '选择药物',
    'meds.step2': '配送和付款',
    'meds.step3': '确认',
    'meds.statusUpdate': '配送状态已更新',
    
    'health.title': '健康检查',
    'health.bp': '血压',
    'health.bp.desc': '测量您的血压',
    'health.weight': '身高和体重',
    'health.weight.desc': '记录您的测量数据',
    'health.back': '返回菜单',
    'health.result': '您的结果',
    'health.normal': '正常',
    'health.date': '测量日期',
    'health.pastResults': '过往结果',
    'health.saved': '结果保存成功',
    'health.saveFailed': '保存结果失败',
    
    'teleconsult.title': '远程医疗',
    'teleconsult.subtitle': '在家与医生交谈',
    'teleconsult.polyclinic': '综合诊所医生',
    'teleconsult.hospital': '医院专科医生',
    'teleconsult.serious': '如有严重情况，请亲自前往综合诊所或医院。',
    'teleconsult.payment': '付款方式',
    'teleconsult.card': '刷卡付款',
    'teleconsult.cash': '账单寄到家（现金）',
    'teleconsult.start': '开始咨询',
    'teleconsult.connecting': '正在连接医生...',
    'teleconsult.connected': '咨询已开始',
    'teleconsult.connected.desc': '您的视频咨询已在新标签页中打开。',
    'teleconsult.failed': '连接失败',
    'teleconsult.failed.desc': '无法启动远程医疗，请重试。',
    'teleconsult.tryAgain': '重试',
    'teleconsult.goBack': '返回',
    'teleconsult.returnDashboard': '返回主页',
    'teleconsult.selectType': '选择咨询类型',
    'teleconsult.continuePayment': '继续付款',
    'teleconsult.payByCard': '刷卡付款',
    'teleconsult.billHome': '账单寄到家',
    'teleconsult.cardPayment': '刷卡付款',
    'teleconsult.cardNumber': '卡号',
    'teleconsult.cardHolder': '持卡人姓名',
    'teleconsult.expiry': '有效期',
    'teleconsult.totalAmount': '总金额',
    'teleconsult.processing': '处理付款中...',
    'teleconsult.payStart': '付款并开始咨询',
    'teleconsult.securePayment': '您的付款通过SSL加密保护',
    'teleconsult.billCash': '账单寄到家（现金付款）',
    'teleconsult.billDelivery': '账单寄送',
    'teleconsult.billInfo': '账单将寄送到您的地址。在3-5个工作日内收到后现金付款。',
    'teleconsult.fullName': '全名',
    'teleconsult.blockNo': '门牌号',
    'teleconsult.unitNo': '单位号',
    'teleconsult.street': '街道名称',
    'teleconsult.postalCode': '邮政编码',
    'teleconsult.amountDue': '应付金额（稍后付款）',
    'teleconsult.confirming': '确认中...',
    'teleconsult.confirmStart': '确认并开始咨询',
    'teleconsult.agreePayBill': '继续即表示您同意在账单到达后付款。',
    'teleconsult.consultFee': '咨询费用',
    'teleconsult.free': '免费',
    'teleconsult.subsidisedRate': '{cardType}持卡人补贴价',
    'teleconsult.polyclinicDoctor': '综合诊所医生',
    'teleconsult.hospitalSpecialist': '医院专科医生',
    
    'community.title': '社区活动',
    'community.upcoming': '即将举行的活动',
    'community.past': '过往活动',
    'community.signup': '报名',
    'community.signed': '已报名',
    'community.reviews': '评价',
    'community.points': '积分',
    
    'profile.title': '我的资料',
    'profile.chas': 'CHAS卡类型',
    'profile.points': '总积分',
    'profile.history': '参与记录',
    'profile.rewards': '兑换奖励',
    'profile.voucher': '礼券',
    'profile.redeem': '兑换',
    
    'access.translate': '翻译',
    'access.voice': '语音指南',
    'access.voiceOn': '语音开启',
    'access.voiceOff': '语音关闭',
    
    'common.back': '返回',
    'common.next': '下一步',
    'common.done': '完成',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.logout': '登出',
  },
  ms: {
    'scan.title': 'Selamat Datang',
    'scan.subtitle': 'Sila imbas kad IC / CHAS anda untuk meneruskan',
    'scan.instruction': 'Letakkan kad anda pada pengimbas',
    'scan.scanning': 'Mengimbas...',
    'scan.success': 'Imbasan berjaya!',
    'scan.loading': 'Memuatkan profil anda...',
    
    'lang.title': 'Pilih Bahasa Anda',
    'lang.subtitle': 'Pilih bahasa pilihan anda',
    
    'dashboard.welcome': 'Selamat Datang',
    'dashboard.title': 'Bagaimana kami boleh membantu anda hari ini?',
    'dashboard.health': 'Pemeriksaan Kesihatan',
    'dashboard.health.desc': 'Periksa tekanan darah, tinggi & berat badan',
    'dashboard.teleconsult': 'Telekonsultasi',
    'dashboard.teleconsult.desc': 'Berbual dengan doktor dalam talian',
    'dashboard.community': 'Program Komuniti',
    'dashboard.community.desc': 'Sertai ceramah & aktiviti kesihatan',
    'dashboard.profile': 'Profil Saya',
    'dashboard.profile.desc': 'Lihat mata & ganjaran anda',
    'dashboard.medications': 'Ubat Anda',
    'dashboard.medications.desc': 'Lihat ubat yang ditetapkan',
    
    // Medications
    'meds.title': 'Ubat Anda',
    'meds.yourMeds': 'Ubat yang Ditetapkan',
    'meds.pastMeds': 'Ubat Lepas',
    'meds.pastMedsDesc': 'Preskripsi sedang berjalan dan selesai anda',
    'meds.orderMeds': 'Pesan Ubat',
    'meds.orderMedsDesc': 'Pilih ubat untuk dipesan semula',
    'meds.lastOrder': 'Pesanan terakhir',
    'meds.perBox': 'sekotak',
    'meds.tablets': 'tablet',
    'meds.purpose.bp': 'Pengurusan tekanan darah',
    'meds.purpose.chronic': 'Sokongan penyakit kronik',
    'meds.purpose.digestive': 'Sokongan kesihatan pencernaan',
    'meds.purpose.general': 'Sokongan kesihatan umum',
    'meds.status.ongoing': 'Sedang Berjalan',
    'meds.status.completed': 'Selesai',
    'meds.status.upcoming': 'Akan Datang',
    'meds.delivery.scheduled': 'Dijadualkan untuk penghantaran ke rumah',
    'meds.delivery.ready': 'Sedia untuk diambil',
    'meds.delivery.shipped': 'Dalam perjalanan',
    'meds.delivery.delivered': 'Telah dihantar',
    'meds.prescriber.polyclinic': 'Ditetapkan oleh doktor Poliklinik',
    'meds.prescriber.hospital': 'Ditetapkan oleh Pakar Hospital',
    'meds.deliveryTitle': 'Pilihan Penghantaran',
    'meds.deliveryInfo': 'Ubat dari telekonsultasi boleh dihantar ke rumah anda.',
    'meds.delivery.home': 'Penghantaran ke Rumah',
    'meds.delivery.clinic': 'Ambil di Klinik',
    'meds.paymentTitle': 'Pilihan Pembayaran',
    'meds.payment.card': 'Pembayaran Kad',
    'meds.payment.bill': 'Bayar Kemudian',
    'meds.payment.billDesc': 'Bil dihantar untuk pembayaran tunai',
    'meds.disclaimer': 'Maklumat ubat yang ditunjukkan di sini adalah untuk rujukan sahaja. Sila ikut arahan yang diberikan oleh doktor atau ahli farmasi anda.',
    'meds.selectClinic': 'Pilih Klinik Pengambilan',
    'meds.orderSummary': 'Ringkasan Pesanan',
    'meds.subtotal': 'Jumlah Kecil',
    'meds.chasSubsidy': 'Subsidi CHAS',
    'meds.deliveryFee': 'Yuran Penghantaran',
    'meds.selfCollection': 'Pengambilan Sendiri',
    'meds.free': 'PERCUMA',
    'meds.total': 'Jumlah',
    'meds.cardPayment': 'Pembayaran Kad',
    'meds.cardNumber': 'Nombor Kad',
    'meds.cardHolder': 'Nama Pemegang Kad',
    'meds.expiryDate': 'Tarikh Luput',
    'meds.totalAmount': 'Jumlah Keseluruhan',
    'meds.processing': 'Memproses Pembayaran...',
    'meds.payConfirm': 'Bayar & Sahkan Pesanan',
    'meds.securePayment': 'Pembayaran anda dilindungi dengan penyulitan SSL',
    'meds.billCash': 'Bil ke Rumah (Bayaran Tunai)',
    'meds.billDeliveryTitle': 'Penghantaran Bil Pembayaran',
    'meds.billDeliveryInfo': 'Bil pembayaran akan dihantar bersama ubat anda. Bayar secara tunai apabila ia tiba.',
    'meds.billClinicInfo': 'Bayar di kaunter klinik semasa mengambil ubat anda.',
    'meds.fullName': 'Nama Penuh',
    'meds.blockNo': 'No. Blok/Rumah',
    'meds.unitNo': 'No. Unit',
    'meds.street': 'Nama Jalan',
    'meds.postalCode': 'Poskod',
    'meds.amountDue': 'Jumlah Perlu Dibayar (Bayar Kemudian)',
    'meds.confirming': 'Mengesahkan...',
    'meds.confirmOrder': 'Sahkan Pesanan',
    'meds.agreePayBill': 'Dengan meneruskan, anda bersetuju untuk membayar apabila pesanan tiba.',
    'meds.collectAt': 'Ambil di klinik yang dipilih',
    'meds.clinicAddress': 'Sila bawa kad IC/CHAS anda',
    'meds.orderPlaced': 'Pesanan Berjaya Dibuat',
    'meds.orderPlacedDesc': 'Pesanan ubat anda telah disahkan.',
    'meds.continuePayment': 'Teruskan ke Pembayaran',
    'meds.step1': 'Pilih Ubat',
    'meds.step2': 'Penghantaran & Pembayaran',
    'meds.step3': 'Pengesahan',
    'meds.statusUpdate': 'Status Penghantaran Dikemaskini',
    
    'health.title': 'Pemeriksaan Kesihatan',
    'health.bp': 'Tekanan Darah',
    'health.bp.desc': 'Ukur tekanan darah anda',
    'health.weight': 'Tinggi & Berat',
    'health.weight.desc': 'Rekod ukuran anda',
    'health.back': 'Kembali ke Menu',
    'health.result': 'Keputusan Anda',
    'health.normal': 'Normal',
    'health.date': 'Diukur pada',
    'health.pastResults': 'Keputusan Lepas',
    'health.saved': 'Keputusan berjaya disimpan',
    'health.saveFailed': 'Gagal menyimpan keputusan',
    
    'teleconsult.title': 'Telekonsultasi',
    'teleconsult.subtitle': 'Berbual dengan doktor dari rumah',
    'teleconsult.polyclinic': 'Doktor Poliklinik',
    'teleconsult.hospital': 'Pakar Hospital',
    'teleconsult.serious': 'Untuk keadaan serius, sila kunjungi poliklinik atau hospital secara peribadi.',
    'teleconsult.payment': 'Pilihan Pembayaran',
    'teleconsult.card': 'Bayar dengan Kad',
    'teleconsult.cash': 'Bil ke Rumah (Tunai)',
    'teleconsult.start': 'Mula Konsultasi',
    'teleconsult.connecting': 'Menyambung kepada doktor...',
    'teleconsult.connected': 'Konsultasi Dimulakan',
    'teleconsult.connected.desc': 'Konsultasi video anda telah dibuka dalam tab pelayar baharu.',
    'teleconsult.failed': 'Sambungan Gagal',
    'teleconsult.failed.desc': 'Tidak dapat memulakan telekonsultasi. Sila cuba lagi.',
    'teleconsult.tryAgain': 'Cuba Lagi',
    'teleconsult.goBack': 'Kembali',
    'teleconsult.returnDashboard': 'Kembali ke Papan Pemuka',
    'teleconsult.selectType': 'Pilih Jenis Konsultasi',
    'teleconsult.continuePayment': 'Teruskan ke Pembayaran',
    'teleconsult.payByCard': 'Bayar dengan Kad',
    'teleconsult.billHome': 'Bil ke Rumah',
    'teleconsult.cardPayment': 'Pembayaran Kad',
    'teleconsult.cardNumber': 'Nombor Kad',
    'teleconsult.cardHolder': 'Nama Pemegang Kad',
    'teleconsult.expiry': 'Tarikh Luput',
    'teleconsult.totalAmount': 'Jumlah Keseluruhan',
    'teleconsult.processing': 'Memproses Pembayaran...',
    'teleconsult.payStart': 'Bayar & Mula Konsultasi',
    'teleconsult.securePayment': 'Pembayaran anda dilindungi dengan penyulitan SSL',
    'teleconsult.billCash': 'Bil ke Rumah (Bayaran Tunai)',
    'teleconsult.billDelivery': 'Penghantaran Bil Pembayaran',
    'teleconsult.billInfo': 'Bil pembayaran akan dihantar ke alamat anda. Bayar secara tunai apabila ia tiba dalam 3-5 hari bekerja.',
    'teleconsult.fullName': 'Nama Penuh',
    'teleconsult.blockNo': 'No. Blok/Rumah',
    'teleconsult.unitNo': 'No. Unit',
    'teleconsult.street': 'Nama Jalan',
    'teleconsult.postalCode': 'Poskod',
    'teleconsult.amountDue': 'Jumlah Perlu Dibayar (Bayar Kemudian)',
    'teleconsult.confirming': 'Mengesahkan...',
    'teleconsult.confirmStart': 'Sahkan & Mula Konsultasi',
    'teleconsult.agreePayBill': 'Dengan meneruskan, anda bersetuju untuk membayar bil apabila ia tiba di alamat anda.',
    'teleconsult.consultFee': 'Yuran Konsultasi',
    'teleconsult.free': 'PERCUMA',
    'teleconsult.subsidisedRate': 'Kadar subsidi untuk pemegang kad {cardType}',
    'teleconsult.polyclinicDoctor': 'Doktor Poliklinik',
    'teleconsult.hospitalSpecialist': 'Pakar Hospital',
    
    'community.title': 'Program Komuniti',
    'community.upcoming': 'Acara Akan Datang',
    'community.past': 'Acara Lepas',
    'community.signup': 'Daftar',
    'community.signed': 'Telah Daftar',
    'community.reviews': 'Ulasan',
    'community.points': 'mata',
    
    'profile.title': 'Profil Saya',
    'profile.chas': 'Jenis Kad CHAS',
    'profile.points': 'Jumlah Mata',
    'profile.history': 'Sejarah Penyertaan',
    'profile.rewards': 'Tebus Ganjaran',
    'profile.voucher': 'Baucar',
    'profile.redeem': 'Tebus',
    
    'access.translate': 'Terjemah',
    'access.voice': 'Panduan Suara',
    'access.voiceOn': 'Suara Hidup',
    'access.voiceOff': 'Suara Mati',
    
    'common.back': 'Kembali',
    'common.next': 'Seterusnya',
    'common.done': 'Selesai',
    'common.cancel': 'Batal',
    'common.confirm': 'Sahkan',
    'common.logout': 'Log Keluar',
  },
  ta: {
    'scan.title': 'வரவேற்கிறோம்',
    'scan.subtitle': 'தொடர உங்கள் IC / CHAS அட்டையை ஸ்கேன் செய்யவும்',
    'scan.instruction': 'உங்கள் அட்டையை ஸ்கேனரில் வைக்கவும்',
    'scan.scanning': 'ஸ்கேன் செய்கிறது...',
    'scan.success': 'ஸ்கேன் வெற்றி!',
    'scan.loading': 'உங்கள் சுயவிவரத்தை ஏற்றுகிறது...',
    
    'lang.title': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    'lang.subtitle': 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    
    'dashboard.welcome': 'வரவேற்கிறோம்',
    'dashboard.title': 'இன்று நாங்கள் உங்களுக்கு எவ்வாறு உதவ முடியும்?',
    'dashboard.health': 'சுகாதார பரிசோதனைகள்',
    'dashboard.health.desc': 'இரத்த அழுத்தம், உயரம் & எடையை சரிபார்க்கவும்',
    'dashboard.teleconsult': 'தொலை ஆலோசனை',
    'dashboard.teleconsult.desc': 'ஆன்லைனில் மருத்துவரிடம் பேசுங்கள்',
    'dashboard.community': 'சமூக திட்டங்கள்',
    'dashboard.community.desc': 'சுகாதார பேச்சுக்கள் & செயல்பாடுகளில் சேரவும்',
    'dashboard.profile': 'எனது சுயவிவரம்',
    'dashboard.profile.desc': 'உங்கள் புள்ளிகள் & வெகுமதிகளைப் பார்க்கவும்',
    'dashboard.medications': 'உங்கள் மருந்துகள்',
    'dashboard.medications.desc': 'பரிந்துரைக்கப்பட்ட மருந்துகளைப் பார்க்கவும்',
    
    // Medications
    'meds.title': 'உங்கள் மருந்துகள்',
    'meds.yourMeds': 'பரிந்துரைக்கப்பட்ட மருந்துகள்',
    'meds.pastMeds': 'கடந்த மருந்துகள்',
    'meds.pastMedsDesc': 'உங்கள் நடைபெறும் மற்றும் நிறைவடைந்த மருந்துச்சீட்டுகள்',
    'meds.orderMeds': 'மருந்துகளை ஆர்டர் செய்யவும்',
    'meds.orderMedsDesc': 'மீண்டும் ஆர்டர் செய்ய மருந்துகளைத் தேர்ந்தெடுக்கவும்',
    'meds.lastOrder': 'கடைசி ஆர்டர்',
    'meds.perBox': 'ஒரு பெட்டிக்கு',
    'meds.tablets': 'மாத்திரைகள்',
    'meds.purpose.bp': 'இரத்த அழுத்த மேலாண்மை',
    'meds.purpose.chronic': 'நாள்பட்ட நோய் ஆதரவு',
    'meds.purpose.digestive': 'செரிமான ஆரோக்கிய ஆதரவு',
    'meds.purpose.general': 'பொது ஆரோக்கிய ஆதரவு',
    'meds.status.ongoing': 'நடைபெற்றுக்கொண்டிருக்கிறது',
    'meds.status.completed': 'நிறைவடைந்தது',
    'meds.status.upcoming': 'வரவிருக்கிறது',
    'meds.delivery.scheduled': 'வீட்டிற்கு டெலிவரி திட்டமிடப்பட்டது',
    'meds.delivery.ready': 'சேகரிக்க தயாராக உள்ளது',
    'meds.delivery.shipped': 'வழியில் உள்ளது',
    'meds.delivery.delivered': 'டெலிவரி செய்யப்பட்டது',
    'meds.prescriber.polyclinic': 'பாலிகிளினிக் மருத்துவரால் பரிந்துரைக்கப்பட்டது',
    'meds.prescriber.hospital': 'மருத்துவமனை நிபுணரால் பரிந்துரைக்கப்பட்டது',
    'meds.deliveryTitle': 'டெலிவரி விருப்பங்கள்',
    'meds.deliveryInfo': 'தொலை ஆலோசனை மருந்துகள் உங்கள் வீட்டிற்கு டெலிவரி செய்யப்படலாம்.',
    'meds.delivery.home': 'வீட்டிற்கு டெலிவரி',
    'meds.delivery.clinic': 'கிளினிக்கில் சேகரிக்கவும்',
    'meds.paymentTitle': 'கட்டண விருப்பங்கள்',
    'meds.payment.card': 'அட்டை கட்டணம்',
    'meds.payment.bill': 'பின்னர் செலுத்தவும்',
    'meds.payment.billDesc': 'பணம் செலுத்த பில் டெலிவரி செய்யப்படும்',
    'meds.disclaimer': 'இங்கு காட்டப்படும் மருந்து தகவல் குறிப்புக்கு மட்டுமே. உங்கள் மருத்துவர் அல்லது மருந்தாளரின் வழிமுறைகளைப் பின்பற்றவும்.',
    'meds.selectClinic': 'சேகரிப்பு கிளினிக் தேர்ந்தெடுக்கவும்',
    'meds.orderSummary': 'ஆர்டர் சுருக்கம்',
    'meds.subtotal': 'துணை மொத்தம்',
    'meds.chasSubsidy': 'CHAS மானியம்',
    'meds.deliveryFee': 'டெலிவரி கட்டணம்',
    'meds.selfCollection': 'சுய சேகரிப்பு',
    'meds.free': 'இலவசம்',
    'meds.total': 'மொத்தம்',
    'meds.cardPayment': 'அட்டை கட்டணம்',
    'meds.cardNumber': 'அட்டை எண்',
    'meds.cardHolder': 'அட்டை வைத்திருப்பவர் பெயர்',
    'meds.expiryDate': 'காலாவதி தேதி',
    'meds.totalAmount': 'மொத்த தொகை',
    'meds.processing': 'கட்டணம் செயலாக்கப்படுகிறது...',
    'meds.payConfirm': 'செலுத்தி ஆர்டரை உறுதிப்படுத்தவும்',
    'meds.securePayment': 'உங்கள் கட்டணம் SSL குறியாக்கத்துடன் பாதுகாக்கப்படுகிறது',
    'meds.billCash': 'வீட்டிற்கு பில் (பண கட்டணம்)',
    'meds.billDeliveryTitle': 'கட்டண பில் டெலிவரி',
    'meds.billDeliveryInfo': 'கட்டண பில் உங்கள் மருந்துகளுடன் அனுப்பப்படும். வரும்போது பணமாக செலுத்தவும்.',
    'meds.billClinicInfo': 'உங்கள் மருந்துகளை சேகரிக்கும் போது கிளினிக் கவுண்டரில் செலுத்தவும்.',
    'meds.fullName': 'முழு பெயர்',
    'meds.blockNo': 'பிளாக்/வீட்டு எண்',
    'meds.unitNo': 'யூனிட் எண்',
    'meds.street': 'தெரு பெயர்',
    'meds.postalCode': 'அஞ்சல் குறியீடு',
    'meds.amountDue': 'செலுத்த வேண்டிய தொகை (பின்னர் செலுத்தவும்)',
    'meds.confirming': 'உறுதிப்படுத்துகிறது...',
    'meds.confirmOrder': 'ஆர்டரை உறுதிப்படுத்தவும்',
    'meds.agreePayBill': 'தொடர்வதன் மூலம், ஆர்டர் வரும்போது செலுத்த ஒப்புக்கொள்கிறீர்கள்.',
    'meds.collectAt': 'தேர்ந்தெடுக்கப்பட்ட கிளினிக்கில் சேகரிக்கவும்',
    'meds.clinicAddress': 'உங்கள் IC/CHAS அட்டையை கொண்டு வரவும்',
    'meds.orderPlaced': 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது',
    'meds.orderPlacedDesc': 'உங்கள் மருந்து ஆர்டர் உறுதிப்படுத்தப்பட்டது.',
    'meds.continuePayment': 'கட்டணத்திற்கு தொடரவும்',
    'meds.step1': 'மருந்துகளைத் தேர்ந்தெடுக்கவும்',
    'meds.step2': 'டெலிவரி & கட்டணம்',
    'meds.step3': 'உறுதிப்படுத்தல்',
    'meds.statusUpdate': 'டெலிவரி நிலை புதுப்பிக்கப்பட்டது',
    
    'health.title': 'சுகாதார பரிசோதனைகள்',
    'health.bp': 'இரத்த அழுத்தம்',
    'health.bp.desc': 'உங்கள் இரத்த அழுத்தத்தை அளவிடுங்கள்',
    'health.weight': 'உயரம் & எடை',
    'health.weight.desc': 'உங்கள் அளவீடுகளை பதிவு செய்யுங்கள்',
    'health.back': 'மெனுவிற்கு திரும்பு',
    'health.result': 'உங்கள் முடிவு',
    'health.normal': 'சாதாரண',
    'health.date': 'அளவிடப்பட்ட தேதி',
    'health.pastResults': 'கடந்த முடிவுகள்',
    'health.saved': 'முடிவு வெற்றிகரமாக சேமிக்கப்பட்டது',
    'health.saveFailed': 'முடிவை சேமிக்க முடியவில்லை',
    
    'teleconsult.title': 'தொலை ஆலோசனை',
    'teleconsult.subtitle': 'வீட்டிலிருந்தே மருத்துவரிடம் பேசுங்கள்',
    'teleconsult.polyclinic': 'பாலிகிளினிக் மருத்துவர்',
    'teleconsult.hospital': 'மருத்துவமனை நிபுணர்',
    'teleconsult.serious': 'தீவிர நிலைகளுக்கு, நேரில் பாலிகிளினிக் அல்லது மருத்துவமனைக்கு செல்லவும்.',
    'teleconsult.payment': 'கட்டண விருப்பங்கள்',
    'teleconsult.card': 'அட்டையில் செலுத்து',
    'teleconsult.cash': 'வீட்டிற்கு பில் (பணம்)',
    'teleconsult.start': 'ஆலோசனையைத் தொடங்கு',
    'teleconsult.connecting': 'மருத்துவருடன் இணைக்கிறது...',
    'teleconsult.connected': 'ஆலோசனை தொடங்கியது',
    'teleconsult.connected.desc': 'உங்கள் வீடியோ ஆலோசனை புதிய உலாவி தாவலில் திறக்கப்பட்டது.',
    'teleconsult.failed': 'இணைப்பு தோல்வி',
    'teleconsult.failed.desc': 'தொலை ஆலோசனையைத் தொடங்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'teleconsult.tryAgain': 'மீண்டும் முயற்சி',
    'teleconsult.goBack': 'பின்செல்',
    'teleconsult.returnDashboard': 'டாஷ்போர்டுக்கு திரும்பு',
    'teleconsult.selectType': 'ஆலோசனை வகையைத் தேர்ந்தெடுக்கவும்',
    'teleconsult.continuePayment': 'கட்டணத்திற்கு தொடரவும்',
    'teleconsult.payByCard': 'அட்டையில் செலுத்து',
    'teleconsult.billHome': 'வீட்டிற்கு பில்',
    'teleconsult.cardPayment': 'அட்டை கட்டணம்',
    'teleconsult.cardNumber': 'அட்டை எண்',
    'teleconsult.cardHolder': 'அட்டை உரிமையாளர் பெயர்',
    'teleconsult.expiry': 'காலாவதி தேதி',
    'teleconsult.totalAmount': 'மொத்த தொகை',
    'teleconsult.processing': 'கட்டணம் செயலாக்கப்படுகிறது...',
    'teleconsult.payStart': 'செலுத்தி ஆலோசனையைத் தொடங்கு',
    'teleconsult.securePayment': 'உங்கள் கட்டணம் SSL குறியாக்கத்தால் பாதுகாக்கப்படுகிறது',
    'teleconsult.billCash': 'வீட்டிற்கு பில் (பண கட்டணம்)',
    'teleconsult.billDelivery': 'கட்டண பில் டெலிவரி',
    'teleconsult.billInfo': 'கட்டண பில் உங்கள் முகவரிக்கு அனுப்பப்படும். 3-5 வேலை நாட்களில் வரும்போது பணமாக செலுத்தவும்.',
    'teleconsult.fullName': 'முழு பெயர்',
    'teleconsult.blockNo': 'தொகுதி/வீட்டு எண்',
    'teleconsult.unitNo': 'அலகு எண்',
    'teleconsult.street': 'தெரு பெயர்',
    'teleconsult.postalCode': 'அஞ்சல் குறியீடு',
    'teleconsult.amountDue': 'செலுத்த வேண்டிய தொகை (பின்னர் செலுத்து)',
    'teleconsult.confirming': 'உறுதிப்படுத்துகிறது...',
    'teleconsult.confirmStart': 'உறுதிப்படுத்தி ஆலோசனையைத் தொடங்கு',
    'teleconsult.agreePayBill': 'தொடர்வதன் மூலம், பில் உங்கள் முகவரியில் வரும்போது செலுத்த ஒப்புக்கொள்கிறீர்கள்.',
    'teleconsult.consultFee': 'ஆலோசனை கட்டணம்',
    'teleconsult.free': 'இலவசம்',
    'teleconsult.subsidisedRate': '{cardType} அட்டை உரிமையாளர்களுக்கான மானிய விலை',
    'teleconsult.polyclinicDoctor': 'பாலிகிளினிக் மருத்துவர்',
    'teleconsult.hospitalSpecialist': 'மருத்துவமனை நிபுணர்',
    
    'community.title': 'சமூக திட்டங்கள்',
    'community.upcoming': 'வரவிருக்கும் நிகழ்வுகள்',
    'community.past': 'கடந்த நிகழ்வுகள்',
    'community.signup': 'பதிவு செய்',
    'community.signed': 'பதிவு செய்யப்பட்டது',
    'community.reviews': 'மதிப்புரைகள்',
    'community.points': 'புள்ளிகள்',
    
    'profile.title': 'எனது சுயவிவரம்',
    'profile.chas': 'CHAS அட்டை வகை',
    'profile.points': 'மொத்த புள்ளிகள்',
    'profile.history': 'பங்கேற்பு வரலாறு',
    'profile.rewards': 'வெகுமதிகளை பெறுங்கள்',
    'profile.voucher': 'வவுச்சர்',
    'profile.redeem': 'பெறு',
    
    'access.translate': 'மொழிபெயர்',
    'access.voice': 'குரல் வழிகாட்டி',
    'access.voiceOn': 'குரல் இயக்கம்',
    'access.voiceOff': 'குரல் நிறுத்தம்',
    
    'common.back': 'பின்செல்',
    'common.next': 'அடுத்து',
    'common.done': 'முடிந்தது',
    'common.cancel': 'ரத்து',
    'common.confirm': 'உறுதிப்படுத்து',
    'common.logout': 'வெளியேறு',
  },
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const [user, setUser] = useState<UserProfile | null>(null);
  const [isVoiceEnabled, setIsVoiceEnabled] = useState(false);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <AppContext.Provider
      value={{
        language,
        setLanguage,
        user,
        setUser,
        isVoiceEnabled,
        setIsVoiceEnabled,
        t,
      }}
    >
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}
