-- Add image_url column to rewards table
ALTER TABLE public.rewards ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Clear existing rewards for fresh setup
DELETE FROM public.rewards;

-- Insert Tier 1 rewards (Certificates - 30 events required)
INSERT INTO public.rewards (title, title_zh, title_ms, title_ta, description, description_zh, description_ms, description_ta, points_cost, tier, max_quantity, display_order, is_active, image_url) VALUES
('Certificate of Community Care Participation', '社区关怀参与证书', 'Sijil Penyertaan Penjagaan Komuniti', 'சமூக பராமரிப்பு பங்கேற்பு சான்றிதழ்', 'Entry-level recognition for first-time participants in raising CCN awareness', '新参与者提高社区关怀网络意识的入门级认可', 'Pengiktirafan peringkat permulaan untuk peserta kali pertama dalam meningkatkan kesedaran CCN', 'CCN விழிப்புணர்வை உயர்த்துவதில் முதல்முறை பங்கேற்பாளர்களுக்கான ஆரம்ப நிலை அங்கீகாரம்', 100, 1, 1, 1, true, '/assets/badges/tier1-participation.png'),
('Certificate of Community Care Support', '社区关怀支持证书', 'Sijil Sokongan Penjagaan Komuniti', 'சமூக பராமரிப்பு ஆதரவு சான்றிதழ்', 'Recognition for consistent involvement and ongoing support for CCN awareness', '持续参与和支持社区关怀网络意识的认可', 'Pengiktirafan untuk penglibatan konsisten dan sokongan berterusan untuk kesedaran CCN', 'CCN விழிப்புணர்வுக்கான நிலையான ஈடுபாடு மற்றும் தொடர்ச்சியான ஆதரவுக்கான அங்கீகாரம்', 200, 1, 1, 2, true, '/assets/badges/tier1-support.png'),
('Certificate of Community Contribution', '社区贡献证书', 'Sijil Sumbangan Komuniti', 'சமூக பங்களிப்பு சான்றிதழ்', 'Milestone recognition for meaningful impact and demonstrated commitment to community care', '对社区关怀有重大影响和承诺的里程碑认可', 'Pengiktirafan pencapaian untuk impak bermakna dan komitmen terhadap penjagaan komuniti', 'அர்த்தமுள்ள தாக்கம் மற்றும் சமூக பராமரிப்புக்கான அர்ப்பணிப்புக்கான மைல்கல் அங்கீகாரம்', 350, 1, 1, 3, true, '/assets/badges/tier1-contribution.png'),
('Certificate of Community Care Advocacy', '社区关怀倡导证书', 'Sijil Advokasi Penjagaan Komuniti', 'சமூக பராமரிப்பு வக்காலத்து சான்றிதழ்', 'Highest Tier-1 recognition for trusted and sustained contributors actively advocating for CCN', '对积极倡导社区关怀网络的可信赖持续贡献者的最高一级认可', 'Pengiktirafan tertinggi Tier-1 untuk penyumbang yang dipercayai dan berterusan', 'CCN-க்காக தீவிரமாக வக்காலத்து செய்யும் நம்பகமான மற்றும் நிலையான பங்களிப்பாளர்களுக்கான உயர்ந்த Tier-1 அங்கீகாரம்', 500, 1, 1, 4, true, '/assets/badges/tier1-advocacy.png');

-- Insert Tier 2 rewards (Achievement Badges - 60 events required)
INSERT INTO public.rewards (title, title_zh, title_ms, title_ta, description, description_zh, description_ms, description_ta, points_cost, tier, max_quantity, display_order, is_active, image_url) VALUES
('Neighbourhood Care Pledge', '邻里关怀承诺', 'Ikrar Penjagaan Kejiranan', 'அக்கம்பக்க பராமரிப்பு உறுதிமொழி', 'Commit to supporting community care awareness in your neighbourhood', '承诺在您的社区支持社区关怀意识', 'Komited untuk menyokong kesedaran penjagaan komuniti di kejiranan anda', 'உங்கள் பகுதியில் சமூக பராமரிப்பு விழிப்புணர்வை ஆதரிக்க உறுதியளிக்கவும்', 150, 2, 1, 1, true, '/assets/badges/tier2-pledge.png'),
('Community Care Supporter Badge', '社区关怀支持者徽章', 'Lencana Penyokong Penjagaan Komuniti', 'சமூக பராமரிப்பு ஆதரவாளர் பேட்ஜ்', 'Recognition as a supporter of CCN values and initiatives', '作为社区关怀网络价值观和倡议支持者的认可', 'Pengiktirafan sebagai penyokong nilai dan inisiatif CCN', 'CCN மதிப்புகள் மற்றும் முயற்சிகளின் ஆதரவாளராக அங்கீகாரம்', 300, 2, 1, 2, true, '/assets/badges/tier2-supporter.png'),
('Care Awareness Advocate Badge', '关怀意识倡导者徽章', 'Lencana Penyokong Kesedaran Penjagaan', 'பராமரிப்பு விழிப்புணர்வு வக்காலத்து பேட்ஜ்', 'For actively helping spread awareness of CCN services in the community', '积极帮助传播社区关怀网络服务意识的认可', 'Untuk membantu menyebarkan kesedaran perkhidmatan CCN secara aktif', 'சமூகத்தில் CCN சேவைகளின் விழிப்புணர்வை பரப்ப உதவுவதற்காக', 450, 2, 1, 3, true, '/assets/badges/tier2-advocate.png'),
('Neighbourhood Connector Badge', '邻里连接者徽章', 'Lencana Penghubung Kejiranan', 'அக்கம்பக்க இணைப்பாளர் பேட்ஜ்', 'Helping connect people to community care resources - the core CCN mission', '帮助人们连接社区关怀资源 - 社区关怀网络的核心使命', 'Membantu menghubungkan orang dengan sumber penjagaan komuniti', 'மக்களை சமூக பராமரிப்பு வளங்களுடன் இணைக்க உதவுதல்', 600, 2, 1, 4, true, '/assets/badges/tier2-connector.png'),
('Trusted Community Member Badge', '可信赖社区成员徽章', 'Lencana Ahli Komuniti Dipercayai', 'நம்பகமான சமூக உறுப்பினர் பேட்ஜ்', 'Recognised as reliable and responsible in upholding community care values', '被认可为可靠和负责任地维护社区关怀价值观', 'Diiktiraf sebagai boleh dipercayai dan bertanggungjawab', 'சமூக பராமரிப்பு மதிப்புகளை நிலைநிறுத்துவதில் நம்பகமான மற்றும் பொறுப்பான என அங்கீகரிக்கப்பட்டது', 800, 2, 1, 5, true, '/assets/badges/tier2-trusted.png'),
('Community Care Ambassador Badge', '社区关怀大使徽章', 'Lencana Duta Penjagaan Komuniti', 'சமூக பராமரிப்பு தூதுவர் பேட்ஜ்', 'The highest recognition - representing CCN values within your neighbourhood', '最高认可 - 在您的社区代表社区关怀网络价值观', 'Pengiktirafan tertinggi - mewakili nilai CCN dalam kejiranan anda', 'உயர்ந்த அங்கீகாரம் - உங்கள் பகுதியில் CCN மதிப்புகளை பிரதிநிதித்துவப்படுத்துதல்', 1000, 2, 1, 6, true, '/assets/badges/tier2-ambassador.png');